export const navItems = [
  { href: "/seo/overview", label: "نمای کلی", section: "overview" },
  { href: "/seo/products", label: "برج کنترل محصولات", section: "products" },
  { href: "/seo/competitors-serp", label: "تحلیل رقبا و SERP", section: "competitors" },
  { href: "/seo/live-editor", label: "ویرایشگر و دستیار زنده", section: "editor" },
  { href: "/seo/keywords-content", label: "کلمات کلیدی و محتوا", section: "keywords" },
  { href: "/seo/images-alt", label: "تصاویر و ALT", section: "images" },
  { href: "/seo/schema-preview", label: "اسکیما و پیش‌نمایش", section: "schema" },
  { href: "/seo/categories-links", label: "دسته‌بندی‌ها و لینک‌سازی", section: "categories" },
  { href: "/seo/technical-health", label: "سلامت فنی و کرال", section: "technical" },
  { href: "/seo/rank-tracking", label: "ردیابی رتبه", section: "rank" },
  { href: "/seo/control-tower", label: "مرکز فرمان Agentها", section: "agents" },
  { href: "/seo/settings", label: "قوانین و تنظیمات", section: "settings" },
  { href: "/seo/reports", label: "گزارش‌ها", section: "reports" },
  { href: "/seo/control-tower#approval", label: "تأیید و بازگشت", section: "approval" },
] as const;
