"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useLocale } from "next-intl";

import { apiGet, apiMutate } from "#/lib/queries/api-client";

export interface GovernanceOverview { policyCount: number; agentCount: number; activeAgentCount: number; killedAgentCount: number; pendingApprovals: number; ledgerEntries: number; ledgerLastSequence: number; reviewedShadowObservations: number; autonomyDistribution: Array<{ level: number; count: number }>; ledgerIntegrity: { ok: boolean; checked: number; lastSequence?: number; lastHash?: string; reason?: string | null }; }
export interface GovernanceAction { key: string; labelFa: string; labelEn: string; domain: string; risk: string; reversibility: string; maxAutonomy: number; defaultEffect: string; stepUpByDefault?: boolean; }
export interface GovernancePolicy { id: number; policyKey: string; version: number; name: string; description: string | null; actionPattern: string; effect: string; priority: number; autonomyCeiling: number | null; enabled: boolean; reason: string; contentHash: string; createdAt: string; }
export interface GovernanceAgent { id: number; principalKey: string; name: string; allowedActions: string[]; prohibitedActions: string[]; dataAccessClasses: string[]; autonomyLevel: number; budgetLimitMinor: number | null; budgetCurrency: string | null; budgetSpentMinor: number; enabled: boolean; killSwitch: boolean; version: number; createdAt: string; updatedAt: string; }
export interface GovernanceApproval { id: number; reference: string; actionKey: string; resourceType: string | null; resourceId: string | null; requestedByUserId: number | null; reason: string; requestHash: string; workflowKind: string; separationOfDuties: boolean; status: string; currentStep: number; expiresAt: string; createdAt: string; steps: Array<{ id: number; index: number; label: string; assignedUserId: number | null; quorum: number; status: string }>; decisions: Array<{ id: number; decision: string; actorUserId: number | null; delegatedToUserId: number | null; reason: string; createdAt: string }>; }
export interface GovernanceLedger { id: number; sequence: number; eventId: string; actorType: string; actionKey: string; resourceType: string | null; resourceId: string | null; reason: string; resultStatus: string; previousHash: string; entryHash: string; occurredAt: string; }
export interface GovernanceShadow { id: number; agentPrincipalId: number | null; actionKey: string; autonomyStage: number; proposalHash: string; humanDecision: string | null; policyDigest: string | null; reviewedAt: string | null; createdAt: string; }

const root = ["admin", "governance"] as const;
const emptyOverview: GovernanceOverview = { policyCount: 0, agentCount: 0, activeAgentCount: 0, killedAgentCount: 0, pendingApprovals: 0, ledgerEntries: 0, ledgerLastSequence: 0, reviewedShadowObservations: 0, autonomyDistribution: [0, 1, 2, 3, 4, 5].map((level) => ({ level, count: 0 })), ledgerIntegrity: { ok: true, checked: 0 } };
const invalidate = (client: ReturnType<typeof useQueryClient>) => () => client.invalidateQueries({ queryKey: root });

export function useGovernanceOverview() { const locale = useLocale(); return useQuery({ queryKey: [...root, "overview", locale], queryFn: ({ signal }) => apiGet<{ data: GovernanceOverview }>("governance/overview", { locale, signal }), select: (v) => v.data, initialData: { data: emptyOverview }, refetchInterval: 30_000 }); }
export function useGovernanceRegistry() { const locale = useLocale(); return useQuery({ queryKey: [...root, "registry", locale], queryFn: ({ signal }) => apiGet<{ data: { actions: GovernanceAction[] } }>("governance/registry", { locale, signal }), select: (v) => v.data, initialData: { data: { actions: [] } }, staleTime: 600_000 }); }
export function useGovernancePolicies() { const locale = useLocale(); return useQuery({ queryKey: [...root, "policies", locale], queryFn: ({ signal }) => apiGet<{ data: GovernancePolicy[] }>("governance/policies", { locale, signal }), select: (v) => v.data }); }
export function useGovernanceAgents() { const locale = useLocale(); return useQuery({ queryKey: [...root, "agents", locale], queryFn: ({ signal }) => apiGet<{ data: GovernanceAgent[] }>("governance/agents", { locale, signal }), select: (v) => v.data }); }
export function useGovernanceApprovals() { const locale = useLocale(); return useQuery({ queryKey: [...root, "approvals", locale], queryFn: ({ signal }) => apiGet<{ data: GovernanceApproval[] }>("governance/approvals", { locale, signal }), select: (v) => v.data, refetchInterval: 15_000 }); }
export function useGovernanceLedger() { const locale = useLocale(); return useQuery({ queryKey: [...root, "ledger", locale], queryFn: ({ signal }) => apiGet<{ data: GovernanceLedger[] }>("governance/ledger", { locale, signal }), select: (v) => v.data }); }
export function useGovernanceShadow() { const locale = useLocale(); return useQuery({ queryKey: [...root, "shadow", locale], queryFn: ({ signal }) => apiGet<{ data: GovernanceShadow[]; readiness: { criteriaVersion: string; reviewed: number; agreementRate: number; failureRate: number; currentStage: number; eligible: boolean; recommendedStage: number } }>("governance/shadow", { locale, signal }) }); }

export function useCreatePolicy() { const locale = useLocale(); const client = useQueryClient(); return useMutation({ mutationFn: (body: Record<string, unknown>) => apiMutate("POST", "governance/policies", { locale, body }), onSuccess: invalidate(client) }); }
export function useCreateAgent() { const locale = useLocale(); const client = useQueryClient(); return useMutation({ mutationFn: (body: Record<string, unknown>) => apiMutate("POST", "governance/agents", { locale, body }), onSuccess: invalidate(client) }); }
export function useKillSwitch() { const locale = useLocale(); const client = useQueryClient(); return useMutation({ mutationFn: ({ id, enabled }: { id: number; enabled: boolean }) => apiMutate("POST", `governance/agents/${id}/kill-switch`, { locale, body: { enabled } }), onSuccess: invalidate(client) }); }
export function useCreateApproval() { const locale = useLocale(); const client = useQueryClient(); return useMutation({ mutationFn: (body: Record<string, unknown>) => apiMutate<{ data: GovernanceApproval }>("POST", "governance/approvals", { locale, body }), onSuccess: invalidate(client) }); }
export function useDecideApproval() { const locale = useLocale(); const client = useQueryClient(); return useMutation({ mutationFn: ({ reference, decision, reason }: { reference: string; decision: "approve" | "reject"; reason: string }) => apiMutate("POST", `governance/approvals/${reference}/decision`, { locale, body: { decision, reason } }), onSuccess: invalidate(client) }); }
export function useVerifyLedger() { const locale = useLocale(); const client = useQueryClient(); return useMutation({ mutationFn: () => apiMutate("POST", "governance/ledger/verify", { locale, body: {} }), onSuccess: invalidate(client) }); }
export function useReviewShadow() { const locale = useLocale(); const client = useQueryClient(); return useMutation({ mutationFn: ({ id, humanDecision }: { id: number; humanDecision: "approve" | "reject" | "modify" | "abstain" }) => apiMutate("POST", `governance/shadow/${id}/review`, { locale, body: { humanDecision, outcome: {} } }), onSuccess: invalidate(client) }); }
