import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";

import { DB_ROLES, DEMO_TENANTS, SERVICES, type ServiceDef } from "./catalog";
import { SHARED_CADDY_CA_DIR, spinLogDir } from "./paths";
import { effectivePort, requirePort } from "./ports";
import type { SpinMeta } from "./meta";

/**
 * The render layer: turns a {@link SpinMeta} into the per-spin `.env` files, the Caddyfile, and
 * the observability config. Every value is interpolated through type-checked template literals
 * and resolved with {@link requirePort} (which THROWS on a missing port) rather than a string
 * `{{TOKEN}}` engine — this gives the same loud-failure guarantee the design called for (a null
 * port aborts the spin instead of emitting a broken `reverse_proxy host.docker.internal:` line)
 * while also being compiler-checked, so a typo'd field can't slip through.
 *
 * Canonical per-tenant URLs use the **Caddy TLS** scheme (`<shop>.admin.<slug>.spin.localhost`);
 * the direct-port scheme stays as a fallback. The dual-scheme bug is fixed by making the env
 * (`ADMIN_URL_TEMPLATE`, `CONSOLE_URL`) advertise the same canonical scheme as the handoff/panel.
 */

/** Marker line every generated env file starts with — the `local` clobber guard greps for it. */
export const SPIN_ENV_HEADER_MARKER = "Generated by @calibra/spin";

function envHeader(slug: string): string {
    return `# ${SPIN_ENV_HEADER_MARKER} for spin "${slug}". Safe to edit; re-running spin overwrites.`;
}

/** The spin's Caddy apex domain, e.g. `my-feature.spin.localhost`. */
function spinDomain(meta: SpinMeta): string {
    return `${meta.slug}.spin.localhost`;
}

/**
 * Base URL for a Caddy-fronted host. Uses the TLS scheme when the spin has a `caddyHttps` port
 * and TLS is on; otherwise falls back to the plain-http Caddy port (legacy/`--no-tls` metas).
 */
function caddyBaseUrl(meta: SpinMeta, host: string): string {
    const httpsPort = effectivePort(meta, "caddyHttps");
    if (httpsPort !== null && meta.tls) return `https://${host}:${httpsPort}`;
    const httpPort = effectivePort(meta, "caddyHttp");
    if (httpPort !== null) return `http://${host}:${httpPort}`;
    return `http://${host}`;
}

/** Impersonation target template — `{slug}` is substituted per-tenant by the api controller. */
function adminUrlTemplate(meta: SpinMeta): string {
    const httpsPort = effectivePort(meta, "caddyHttps");
    if (httpsPort !== null && meta.tls) {
        return `https://{slug}.admin.${spinDomain(meta)}:${httpsPort}`;
    }
    /** Direct-port fallback for metas without an edge layer. */
    return `http://{slug}.admin.localhost:${meta.ports.admin}`;
}

/** Where "exit impersonation" returns the platform operator (the control-plane console). */
function consoleUrl(meta: SpinMeta): string {
    const platformPort = effectivePort(meta, "platform");
    const httpsPort = effectivePort(meta, "caddyHttps");
    if (httpsPort !== null && meta.tls) return caddyBaseUrl(meta, `console.${spinDomain(meta)}`);
    return `http://localhost:${platformPort ?? meta.ports.web ?? meta.ports.admin}`;
}

/**
 * Literal hostnames Next's `allowedDevOrigins` must accept for this spin. The apps already
 * declare wildcard globs (`*.admin.*.spin.localhost`, …); these explicit literals — including
 * every seeded tenant in both the Caddy and direct-port schemes — are belt-and-suspenders for
 * multi-tenant cause #2 (Next blocking `/_next` HMR from a per-tenant host).
 */
export function nextDevAllowedOrigins(meta: SpinMeta): string {
    const domain = spinDomain(meta);
    const origins = [`admin.${domain}`, `web.${domain}`, `api.${domain}`, `console.${domain}`];
    for (const tenant of DEMO_TENANTS) {
        origins.push(`${tenant.slug}.admin.${domain}`, `${tenant.slug}.web.${domain}`);
        origins.push(`${tenant.slug}.admin.localhost`, `${tenant.slug}.shops.localhost`);
    }
    return origins.join(",");
}

/** Render `apps/api/.env`. */
export function renderApiEnv(meta: SpinMeta): string {
    const tempoPort = requirePort(meta, "tempo");
    const meiliPort = requirePort(meta, "meilisearch");
    const allowedOrigins = [
        `http://localhost:${meta.ports.admin}`,
        `http://localhost:${meta.ports.web}`,
        caddyBaseUrl(meta, `admin.${spinDomain(meta)}`),
        caddyBaseUrl(meta, `web.${spinDomain(meta)}`),
        caddyBaseUrl(meta, `console.${spinDomain(meta)}`),
    ].join(",");

    const lines = [
        envHeader(meta.slug),
        "TZ=UTC",
        "NODE_ENV=development",
        `PORT=${meta.ports.api}`,
        "HOST=0.0.0.0",
        `APP_NAME=calibra-api-${meta.slug}`,
        "LOG_LEVEL=info",
        `APP_KEY=${requireSecret(meta, "appKey")}`,
        "DB_HOST=localhost",
        `DB_PORT=${meta.ports.db}`,
        `DB_USER=${DB_ROLES.app.user}`,
        `DB_PASSWORD=${DB_ROLES.app.password}`,
        `DB_DATABASE=${DB_ROLES.database}`,
        `DB_ADMIN_USER=${DB_ROLES.admin.user}`,
        `DB_ADMIN_PASSWORD=${DB_ROLES.admin.password}`,
        `DB_SUPERUSER_USER=${DB_ROLES.superuser.user}`,
        `DB_SUPERUSER_PASSWORD=${DB_ROLES.superuser.password}`,
        "SMS_DRIVER=log",
        `ALLOWED_ORIGINS=${allowedOrigins}`,
        `ADMIN_URL_TEMPLATE=${adminUrlTemplate(meta)}`,
        "MAIL_FROM_ADDRESS=ops@calibra.local",
        "MAIL_FROM_NAME=Calibra",
        "MAIL_NOTIFICATIONS_ENABLED=true",
        "SMTP_HOST=localhost",
        `SMTP_PORT=${requirePort(meta, "mailpitSmtp")}`,
        `MAILPIT_WEB_URL=http://localhost:${requirePort(meta, "mailpitWeb")}`,
        "REDIS_HOST=localhost",
        `REDIS_PORT=${requirePort(meta, "redis")}`,
        "TRANSMIT_TRANSPORT=redis",
        "LIMITER_STORE=redis",
        "QUEUE_DRIVER=database",
        "CACHE_DRIVER=redis",
        `MEILISEARCH_HOST=http://localhost:${meiliPort}`,
        `MEILISEARCH_API_KEY=${requireSecret(meta, "meiliMasterKey")}`,
        "DEV_OBSERVABILITY=true",
        `OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:${tempoPort}`,
        `SPIN_API_LOG_PATH=${join(spinLogDir(meta.worktreePath), "api.ndjson")}`,
        ...(meta.glitchtipDsn ? [`GLITCHTIP_DSN=${meta.glitchtipDsn}`] : []),
        "",
    ];
    return lines.join("\n");
}

/** Render `apps/admin/.env.local`. */
export function renderAdminEnv(meta: SpinMeta): string {
    return [
        envHeader(meta.slug),
        `NEXT_PUBLIC_API_BASE_URL=http://localhost:${meta.ports.api}`,
        `NEXT_PUBLIC_SITE_URL=http://localhost:${meta.ports.admin}`,
        "NEXT_PUBLIC_DEFAULT_LOCALE=fa",
        "NEXT_PUBLIC_ADMIN_ROOT=admin.localhost",
        `NEXT_PUBLIC_CONSOLE_URL=${consoleUrl(meta)}`,
        "",
    ].join("\n");
}

/** Render `apps/web/.env.local`. */
export function renderWebEnv(meta: SpinMeta): string {
    return [
        envHeader(meta.slug),
        `NEXT_PUBLIC_API_BASE_URL=http://localhost:${meta.ports.api}`,
        `NEXT_PUBLIC_SITE_URL=http://localhost:${meta.ports.web}`,
        "NEXT_PUBLIC_DEFAULT_LOCALE=fa",
        "NEXT_PUBLIC_SHOPS_ROOT=shops.localhost",
        "NEXT_PUBLIC_TEMPLATE_KEY=default",
        "",
    ].join("\n");
}

/** Render `apps/platform/.env.local`, or `null` when the spin has no platform port. */
export function renderPlatformEnv(meta: SpinMeta): string | null {
    const platformPort = effectivePort(meta, "platform");
    if (platformPort === null) return null;
    return [
        envHeader(meta.slug),
        `NEXT_PUBLIC_API_BASE_URL=http://localhost:${meta.ports.api}`,
        `NEXT_PUBLIC_SITE_URL=http://localhost:${platformPort}`,
        "NEXT_PUBLIC_DEFAULT_LOCALE=fa",
        "NEXT_PUBLIC_GRAFANA_BASE=",
        "",
    ].join("\n");
}

function requireSecret(meta: SpinMeta, key: "appKey" | "meiliMasterKey" | "glitchtipSecretKey"): string {
    const value = meta[key];
    if (!value) throw new Error(`spin "${meta.slug}" meta is missing secret "${key}"`);
    return value;
}

/** Write every per-spin `.env` file into the worktree. */
export async function renderEnvFiles(meta: SpinMeta): Promise<void> {
    await writeFile(join(meta.worktreePath, "apps/api/.env"), renderApiEnv(meta));
    await writeFile(join(meta.worktreePath, "apps/admin/.env.local"), renderAdminEnv(meta));
    await writeFile(join(meta.worktreePath, "apps/web/.env.local"), renderWebEnv(meta));
    const platformEnv = renderPlatformEnv(meta);
    if (platformEnv) {
        await writeFile(join(meta.worktreePath, "apps/platform/.env.local"), platformEnv);
    }
}

function caddyBlock(host: string, upstream: string): string {
    return `${host} {\n    tls internal\n    reverse_proxy ${upstream}\n}\n`;
}

function caddyOnDemandBlock(host: string, upstream: string): string {
    return `${host} {\n    tls internal {\n        on_demand\n    }\n    reverse_proxy ${upstream}\n}\n`;
}

/**
 * Caddy blocks for one service. Host-upstream services route to `host.docker.internal:<port>`
 * (host HMR apps); container services route by compose service name. Tenant-wildcard services
 * (admin, web) emit, in order: the apex (the platform "unknown shop" page), one **explicit
 * block per seeded tenant** (so `tls internal` mints those leaves reliably — the multi-tenant
 * cert-issuance fix), then an **on-demand-TLS wildcard** for ad-hoc tenants.
 */
function serviceCaddyBlocks(meta: SpinMeta, service: ServiceDef): string[] {
    const route = service.caddy;
    if (!route) return [];

    let upstream: string;
    if (route.upstream === "host") {
        const port = service.portRole ? effectivePort(meta, service.portRole) : null;
        if (port === null) return [];
        upstream = `host.docker.internal:${port}`;
    } else {
        upstream = `${route.upstream.service}:${route.upstream.port}`;
    }

    const domain = spinDomain(meta);
    const apexHost = route.subdomain === "" ? domain : `${route.subdomain}.${domain}`;
    const blocks = [caddyBlock(apexHost, upstream)];

    if (route.tenantWildcard) {
        for (const tenant of DEMO_TENANTS) {
            blocks.push(caddyBlock(`${tenant.slug}.${route.subdomain}.${domain}`, upstream));
        }
        blocks.push(caddyOnDemandBlock(`*.${route.subdomain}.${domain}`, upstream));
    }
    return blocks;
}

/**
 * Render the per-spin Caddyfile from the services catalog. Ad-hoc per-tenant certs are issued on
 * demand, authorized by the spin agent's `/api/caddy/ask` endpoint so Caddy only mints leaves for
 * hosts this spin actually owns.
 */
export function renderCaddyfile(meta: SpinMeta): string {
    const agentPort = requirePort(meta, "spinAgent");
    const global = [
        `# ${SPIN_ENV_HEADER_MARKER} for spin "${meta.slug}". Re-run \`pnpm spin\` to regenerate.`,
        "{",
        "    auto_https disable_redirects",
        "    local_certs",
        "    on_demand_tls {",
        `        ask http://host.docker.internal:${agentPort}/api/caddy/ask`,
        "    }",
        "}",
        "",
    ].join("\n");

    const blocks = SERVICES.flatMap((service) => serviceCaddyBlocks(meta, service));
    return `${global}\n${blocks.join("\n")}`;
}

/** Render Prometheus's scrape config — the api on the host plus a self-scrape sanity target. */
export function renderPrometheusConfig(meta: SpinMeta): string {
    return `# ${SPIN_ENV_HEADER_MARKER} for spin "${meta.slug}".
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    spin: ${meta.slug}

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

rule_files:
  - /etc/prometheus/rules/*.yml

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090

  - job_name: calibra-api
    metrics_path: /metrics
    static_configs:
      - targets:
          - host.docker.internal:${meta.ports.api}
        labels:
          service: calibra-api
          spin: ${meta.slug}
`;
}

/** Render Promtail's pipeline — ships the api's ndjson log to Loki with spin/service labels. */
export function renderPromtailConfig(meta: SpinMeta): string {
    return `# ${SPIN_ENV_HEADER_MARKER} for spin "${meta.slug}".
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /run/promtail/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: calibra-api
    static_configs:
      - targets:
          - localhost
        labels:
          job: calibra-api
          service: calibra-api
          spin: ${meta.slug}
          __path__: /var/log/api/*.ndjson
    pipeline_stages:
      - json:
          expressions:
            level: level
            msg: msg
            time: time
            request_id: request_id
      - labels:
          level:
      - timestamp:
          source: time
          format: UnixMs
`;
}

/** Grafana datasource provisioning — Prometheus, Loki, Tempo (container-to-container URLs). */
export function renderGrafanaDatasources(): string {
    return `apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false

  - name: Loki
    uid: loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: false

  - name: Tempo
    uid: tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    editable: false
`;
}

/** Grafana dashboard provisioner — auto-imports the committed dashboards bind-mounted read-only. */
export function renderGrafanaDashboardsProvider(): string {
    return `apiVersion: 1

providers:
  - name: calibra
    orgId: 1
    folder: ''
    type: file
    disableDeletion: false
    allowUiUpdates: true
    options:
      path: /var/lib/grafana/dashboards
      foldersFromFilesStructure: false
`;
}

/**
 * Write the Caddyfile + observability config into `<worktree>/.spin/config/`, and pre-create the
 * data dirs the bind-mounts need (so docker doesn't create them root-owned) plus the shared CA dir.
 */
export async function renderEdgeAndObsConfig(meta: SpinMeta): Promise<void> {
    const configDir = join(meta.worktreePath, ".spin/config");
    await mkdir(join(configDir, "grafana/provisioning/datasources"), { recursive: true });
    await mkdir(join(configDir, "grafana/provisioning/dashboards"), { recursive: true });
    await mkdir(spinLogDir(meta.worktreePath), { recursive: true });
    await mkdir(join(meta.worktreePath, ".spin/data/promtail"), { recursive: true });
    await mkdir(SHARED_CADDY_CA_DIR, { recursive: true });

    await writeFile(join(configDir, "Caddyfile"), renderCaddyfile(meta));
    await writeFile(join(configDir, "prometheus.yml"), renderPrometheusConfig(meta));
    await writeFile(join(configDir, "promtail.yml"), renderPromtailConfig(meta));
    await writeFile(join(configDir, "grafana/provisioning/datasources/datasources.yml"), renderGrafanaDatasources());
    await writeFile(join(configDir, "grafana/provisioning/dashboards/dashboards.yml"), renderGrafanaDashboardsProvider());
}
