import { log } from "../log";

import { capture, run } from "./exec";
import { writeMeta } from "./meta";
import { requirePort } from "./ports";
import type { SpinMeta } from "./meta";

/**
 * Ensure a draft PR exists for a worktree spin. Idempotent: returns early if one is already
 * recorded. Creates an empty bootstrap commit when the branch has no commits yet (so `gh pr
 * create` accepts it), pushes, and opens a draft PR whose body links to the spin dashboard.
 */
export async function ensureDraftPr(meta: SpinMeta): Promise<void> {
    if (meta.prNumber) {
        log.skip(`PR exists (#${meta.prNumber})`);
        return;
    }

    const ahead = Number.parseInt(
        (await capture("git", ["rev-list", "--count", `origin/main..${meta.branch}`], { cwd: meta.worktreePath })).stdout.trim(),
        10,
    );
    if (!Number.isFinite(ahead) || ahead === 0) {
        log.step("PR: empty bootstrap commit");
        await run(
            "git",
            [
                "commit",
                "--allow-empty",
                "-m",
                `chore(spin): bootstrap ${meta.slug}\n\nGenerated by \`pnpm spin\`. Replace this commit with real work, or amend it.`,
            ],
            { cwd: meta.worktreePath },
        );
    }

    log.step("PR: push branch");
    await run("git", ["push", "-u", "origin", meta.branch], { cwd: meta.worktreePath });

    log.step("PR: gh pr create --draft");
    const caddyHttps = requirePort(meta, "caddyHttps");
    const body = [
        `Bootstrapped by \`pnpm spin ${meta.slug}\`.`,
        "",
        `**Spin dashboard:** https://${meta.slug}.spin.localhost:${caddyHttps}/`,
        "",
        `<sub>Teardown: \`pnpm spin stop ${meta.slug}\` · containers + processes only. Add \`--purge --remove\` to wipe everything.</sub>`,
    ].join("\n");
    const result = await capture(
        "gh",
        ["pr", "create", "--draft", "--base", "main", "--head", meta.branch, "--title", `spin/${meta.slug}: WIP`, "--body", body],
        { cwd: meta.worktreePath },
    );
    if (result.exitCode !== 0) {
        throw new Error(`gh pr create failed: ${result.stderr || result.stdout}`);
    }
    const url = result.stdout.trim().split("\n").pop() ?? "";
    const numberMatch = url.match(/\/pull\/(\d+)/);
    meta.prNumber = numberMatch ? Number(numberMatch[1]) : null;
    meta.prUrl = url;
    await writeMeta(meta);
}
