/**
 * Showcase primitive registry. Drives the side nav and the per-primitive landing pages.
 * Add a row whenever a new primitive lands; the showcase shell renders it automatically.
 */

export type ShowcaseTier = "ui" | "composite" | "business";
export type ShowcaseCategory =
    | "layout"
    | "input"
    | "feedback"
    | "navigation"
    | "data"
    | "picker"
    | "badge"
    | "form-field"
    | "doc";

export interface PrimitiveMeta {
    tier: ShowcaseTier;
    name: string;
    label: string;
    category: ShowcaseCategory;
    description: string;
    importPath: string;
    asyncAware: boolean;
}

export const PRIMITIVES: PrimitiveMeta[] = [
    /* Tier 2 — UI primitives */
    {
        tier: "ui",
        name: "button",
        label: "Button",
        category: "input",
        description: "Primary action button. Variants, tones, isLoading, IconButton, ToggleButton.",
        importPath: "#/components/ui/button",
        asyncAware: true,
    },
    {
        tier: "ui",
        name: "badge",
        label: "Badge",
        category: "badge",
        description: "Status / label pill. Tones + dot variant.",
        importPath: "#/components/ui/badge",
        asyncAware: false,
    },
    {
        tier: "ui",
        name: "card",
        label: "Card",
        category: "layout",
        description: "Bounded panel with tones, header, body, footer, isLoading.",
        importPath: "#/components/ui/card",
        asyncAware: true,
    },
    {
        tier: "ui",
        name: "dialog",
        label: "Dialog",
        category: "feedback",
        description: "Centred modal with convenience wrapper + compound subparts.",
        importPath: "#/components/ui/dialog",
        asyncAware: true,
    },
    {
        tier: "ui",
        name: "sheet",
        label: "Sheet",
        category: "feedback",
        description: "Edge-anchored workspace column. RTL-aware via logical sides.",
        importPath: "#/components/ui/sheet",
        asyncAware: true,
    },
    {
        tier: "ui",
        name: "popover",
        label: "Popover",
        category: "feedback",
        description: "Floating popup. Use for click-pinnable surfaces.",
        importPath: "#/components/ui/popover",
        asyncAware: false,
    },
    {
        tier: "ui",
        name: "tooltip",
        label: "Tooltip",
        category: "feedback",
        description: "Hover/focus tooltip. 150ms delay via Provider.",
        importPath: "#/components/ui/tooltip",
        asyncAware: false,
    },
    {
        tier: "ui",
        name: "hover-card",
        label: "HoverCard",
        category: "feedback",
        description: "Hover-reveal preview card. Not for keyboard-essential content.",
        importPath: "#/components/ui/hover-card",
        asyncAware: false,
    },
    {
        tier: "ui",
        name: "dropdown-menu",
        label: "DropdownMenu",
        category: "navigation",
        description: "Menu primitive for row actions / contextual options.",
        importPath: "#/components/ui/dropdown-menu",
        asyncAware: false,
    },
    {
        tier: "ui",
        name: "tabs",
        label: "Tabs",
        category: "navigation",
        description: "Tab strip — default / line / ghost variants.",
        importPath: "#/components/ui/tabs",
        asyncAware: false,
    },
    {
        tier: "ui",
        name: "select",
        label: "Select",
        category: "input",
        description: "Single-select dropdown for fixed enum lists. Loading prop on trigger.",
        importPath: "#/components/ui/select",
        asyncAware: true,
    },
    {
        tier: "ui",
        name: "combobox",
        label: "Combobox / MultiCombobox",
        category: "picker",
        description: "Async searchable picker. Single + multi variants.",
        importPath: "#/components/ui/combobox",
        asyncAware: true,
    },
    {
        tier: "ui",
        name: "input",
        label: "Input",
        category: "form-field",
        description: "Native text input styled to admin form-field language.",
        importPath: "#/components/ui/input",
        asyncAware: false,
    },
    {
        tier: "ui",
        name: "textarea",
        label: "Textarea",
        category: "form-field",
        description: "Native textarea.",
        importPath: "#/components/ui/textarea",
        asyncAware: false,
    },
    {
        tier: "ui",
        name: "label",
        label: "Label",
        category: "form-field",
        description: "Form label with required / optional markers.",
        importPath: "#/components/ui/label",
        asyncAware: false,
    },
    {
        tier: "ui",
        name: "checkbox",
        label: "Checkbox",
        category: "form-field",
        description: "Boolean toggle. Tri-state via indeterminate.",
        importPath: "#/components/ui/checkbox",
        asyncAware: false,
    },
    {
        tier: "ui",
        name: "radio-group",
        label: "RadioGroup",
        category: "form-field",
        description: "Single-choice control. Animated scale indicator.",
        importPath: "#/components/ui/radio-group",
        asyncAware: false,
    },
    {
        tier: "ui",
        name: "switch",
        label: "Switch",
        category: "form-field",
        description: "Binary on/off switch. RTL-aware translate.",
        importPath: "#/components/ui/switch",
        asyncAware: false,
    },
    {
        tier: "ui",
        name: "number-field",
        label: "NumberField",
        category: "form-field",
        description: "Numeric input with steppers + suffix chip. Always LTR for editing.",
        importPath: "#/components/ui/number-field",
        asyncAware: false,
    },
    {
        tier: "ui",
        name: "slider",
        label: "Slider",
        category: "form-field",
        description: "Single + range slider. Inferred thumb count.",
        importPath: "#/components/ui/slider",
        asyncAware: false,
    },
    {
        tier: "ui",
        name: "progress",
        label: "Progress",
        category: "feedback",
        description: "Determinate progress bar. Semantic tones.",
        importPath: "#/components/ui/progress",
        asyncAware: false,
    },
    {
        tier: "ui",
        name: "spinner",
        label: "Spinner",
        category: "feedback",
        description: "Inline loading indicator. Sizes xs..xl.",
        importPath: "#/components/ui/spinner",
        asyncAware: false,
    },
    {
        tier: "ui",
        name: "skeleton",
        label: "Skeleton",
        category: "feedback",
        description: "Placeholder block. Pulse + shimmer animations.",
        importPath: "#/components/ui/skeleton",
        asyncAware: false,
    },
    {
        tier: "ui",
        name: "toast",
        label: "Toast",
        category: "feedback",
        description: "Stacked notifications with tone + promise API.",
        importPath: "#/components/ui/toast",
        asyncAware: true,
    },
    {
        tier: "ui",
        name: "scroll-area",
        label: "ScrollArea",
        category: "layout",
        description: "Styled scrollable container. Slim auto-hiding scrollbar.",
        importPath: "#/components/ui/scroll-area",
        asyncAware: false,
    },
    {
        tier: "ui",
        name: "separator",
        label: "Separator",
        category: "layout",
        description: "Decorative divider (role=none).",
        importPath: "#/components/ui/separator",
        asyncAware: false,
    },
    {
        tier: "ui",
        name: "avatar",
        label: "Avatar",
        category: "feedback",
        description: "Avatar with image + fallback.",
        importPath: "#/components/ui/avatar",
        asyncAware: false,
    },

    /* Tier 3 — Composite primitives */
    {
        tier: "composite",
        name: "calendar",
        label: "Calendar",
        category: "input",
        description: "Jalali-aware calendar body — always rendered inside a Dialog.",
        importPath: "#/components/ui/calendar",
        asyncAware: false,
    },
    {
        tier: "composite",
        name: "date-picker-field",
        label: "DatePickerField",
        category: "input",
        description: "Single-date input opening a Calendar inside a Dialog.",
        importPath: "#/components/ui/date-picker-field",
        asyncAware: false,
    },
    {
        tier: "composite",
        name: "date-range-picker-field",
        label: "DateRangePickerField",
        category: "input",
        description: "Date-range input opening a Calendar inside a Dialog.",
        importPath: "#/components/ui/date-range-picker-field",
        asyncAware: false,
    },
    {
        tier: "composite",
        name: "date-filter-chip",
        label: "DateFilterChip",
        category: "data",
        description: "URL-synced date filter chip for data-grid toolbars.",
        importPath: "#/components/ui/date-filter-chip",
        asyncAware: false,
    },
    {
        tier: "composite",
        name: "data-grid",
        label: "DataGrid",
        category: "data",
        description: "TanStack-based data grid with sticky cols, URL state, density, bulk actions.",
        importPath: "#/components/ui/data-grid",
        asyncAware: true,
    },
    {
        tier: "composite",
        name: "entity-combobox",
        label: "EntityCombobox",
        category: "picker",
        description: "Canonical async-multi-select for entity-shaped data. Base for every business picker.",
        importPath: "#/components/ui/entity-combobox",
        asyncAware: true,
    },
    {
        tier: "composite",
        name: "empty-state",
        label: "EmptyState",
        category: "feedback",
        description: "Settled-with-zero-rows body for lists / grids / picker popups.",
        importPath: "#/components/ui/empty-state",
        asyncAware: false,
    },
    {
        tier: "composite",
        name: "helper-tooltip",
        label: "HelperTooltip",
        category: "feedback",
        description: "The '?' icon next to form labels. Tooltip or Popover variant.",
        importPath: "#/components/ui/helper-tooltip",
        asyncAware: false,
    },
    {
        tier: "composite",
        name: "sticky-action-bar",
        label: "StickyActionBar",
        category: "feedback",
        description: "Floating bottom-center action surface.",
        importPath: "#/components/ui/sticky-action-bar",
        asyncAware: false,
    },
    {
        tier: "composite",
        name: "bulk-selection-bar",
        label: "BulkSelectionBar",
        category: "feedback",
        description: "Selection summary + cancel/delete cluster over StickyActionBar.",
        importPath: "#/components/ui/bulk-selection-bar",
        asyncAware: false,
    },
    {
        tier: "composite",
        name: "onboarding-hint",
        label: "OnboardingHint",
        category: "feedback",
        description: "Dismissable hint banner. Persists via localStorage.",
        importPath: "#/components/ui/onboarding-hint",
        asyncAware: false,
    },
    {
        tier: "composite",
        name: "alert-dialog",
        label: "AlertDialog / ConfirmDialog",
        category: "feedback",
        description: "Confirm dialog (role=alertdialog). No backdrop dismiss.",
        importPath: "#/components/ui/alert-dialog",
        asyncAware: true,
    },
    {
        tier: "composite",
        name: "code-block",
        label: "CodeBlock",
        category: "doc",
        description: "Server-rendered Shiki syntax-highlighted code block.",
        importPath: "#/components/ui/code-block",
        asyncAware: false,
    },

    /* Tier 4 — Business primitives */
    {
        tier: "business",
        name: "product-picker",
        label: "ProductPicker",
        category: "picker",
        description: "Product entity picker wired to product search/resolve.",
        importPath: "#/components/business/product-picker",
        asyncAware: true,
    },
    {
        tier: "business",
        name: "category-picker",
        label: "CategoryPicker",
        category: "picker",
        description: "Category entity picker.",
        importPath: "#/components/business/category-picker",
        asyncAware: true,
    },
    {
        tier: "business",
        name: "brand-picker",
        label: "BrandPicker",
        category: "picker",
        description: "Brand entity picker.",
        importPath: "#/components/business/brand-picker",
        asyncAware: true,
    },
    {
        tier: "business",
        name: "customer-picker",
        label: "CustomerPicker",
        category: "picker",
        description: "Customer entity picker.",
        importPath: "#/components/business/customer-picker",
        asyncAware: true,
    },
    {
        tier: "business",
        name: "status-badge",
        label: "StatusBadge",
        category: "badge",
        description: "Tone-coloured status pill.",
        importPath: "#/components/business/status-badge",
        asyncAware: false,
    },
    {
        tier: "business",
        name: "order-status-badge",
        label: "OrderStatusBadge",
        category: "badge",
        description: "OrderStatus → tone mapping over StatusBadge.",
        importPath: "#/components/business/order-status-badge",
        asyncAware: false,
    },
    {
        tier: "business",
        name: "money-input",
        label: "MoneyInput",
        category: "form-field",
        description: "Numeric input wired to rial / toman conversion + locale digit rendering.",
        importPath: "#/components/business/money-input",
        asyncAware: false,
    },
    {
        tier: "business",
        name: "address-card",
        label: "AddressCard",
        category: "data",
        description: "Address display card.",
        importPath: "#/components/business/address-card",
        asyncAware: false,
    },
    {
        tier: "business",
        name: "address-form",
        label: "AddressForm",
        category: "form-field",
        description: "Address-shape form composing Input / Field.",
        importPath: "#/components/business/address-form",
        asyncAware: false,
    },
    {
        tier: "business",
        name: "stat-card",
        label: "StatCard",
        category: "data",
        description: "KPI tile with delta.",
        importPath: "#/components/business/stat-card",
        asyncAware: false,
    },
    {
        tier: "business",
        name: "sparkline",
        label: "Sparkline",
        category: "data",
        description: "Minimal SVG sparkline.",
        importPath: "#/components/business/sparkline",
        asyncAware: false,
    },
];

export function getByTier(tier: ShowcaseTier): PrimitiveMeta[] {
    return PRIMITIVES.filter((p) => p.tier === tier).sort((a, b) => a.label.localeCompare(b.label));
}

export function getByName(name: string): PrimitiveMeta | undefined {
    return PRIMITIVES.find((p) => p.name === name);
}
