import { Activity, AlertTriangle, BadgeCheck, PackageSearch, Server, ShieldCheck, Sparkles, Tags } from "#/icons";

export const QUALITY_SECTIONS = [
    {
        key: "overview",
        href: "/quality/overview",
        fa: "نمای کلی",
        en: "Overview",
        helpFa: "وضعیت پرونده‌ها، سیگنال‌ها، اقدامات عقب‌افتاده و پوشش بازرسی را بدون عدد ساختگی نشان می‌دهد.",
        helpEn: "Live cases, signals, overdue actions and inspection coverage without fabricated values.",
        icon: ShieldCheck,
    },
    {
        key: "cases",
        href: "/quality/cases",
        fa: "پرونده‌های کیفیت",
        en: "Quality cases",
        helpFa: "مرکز بررسی شواهد، یافته‌ها، اقدام اصلاحی و نتیجه قابل‌اندازه‌گیری.",
        helpEn: "Investigation workspace for evidence, findings, corrective actions and outcomes.",
        icon: BadgeCheck,
    },
    {
        key: "signals",
        href: "/quality/signals",
        fa: "سیگنال‌ها و ناهنجاری‌ها",
        en: "Signals & anomalies",
        helpFa: "هشدارهای قطعی و مخرج‌محور؛ داده ناکافی به‌عنوان هشدار نمایش داده نمی‌شود.",
        helpEn: "Deterministic denominator-aware alerts; insufficient data never becomes an alert.",
        icon: AlertTriangle,
    },
    {
        key: "returns",
        href: "/quality/returns",
        fa: "هوشمندی مرجوعی",
        en: "Returns intelligence",
        helpFa: "نمای تحلیلی روی مرجوعی موجود؛ سیستم مرجوعی دوم ساخته نمی‌شود.",
        helpEn: "Analytical projection over canonical returns, not a second returns system.",
        icon: PackageSearch,
    },
    {
        key: "voc",
        href: "/quality/voc",
        fa: "صدای مشتری",
        en: "Voice of customer",
        helpFa: "مرجوعی، نقد و تیکت را با حفظ متن اصلی به موضوع‌های قابل بررسی طبقه‌بندی می‌کند.",
        helpEn: "Classifies returns, reviews and tickets while preserving canonical raw text.",
        icon: Sparkles,
    },
    {
        key: "suppliers",
        href: "/quality/suppliers",
        fa: "کیفیت تأمین‌کننده",
        en: "Supplier quality",
        helpFa: "زنجیره مستقیم تأمین‌کننده، PO و دریافت فاز ۱۴ فعال است؛ نسبت‌دادن مرجوعی مشتری تا وجود allocation قطعی Lot به سفارش همچنان بسته می‌ماند.",
        helpEn: "Direct Phase 14 supplier, PO and receiving evidence is live; customer-return attribution stays closed until deterministic lot-to-order allocation exists.",
        icon: Activity,
    },
    {
        key: "actions",
        href: "/quality/actions",
        fa: "اقدامات اصلاحی",
        en: "Corrective actions",
        helpFa: "مالک، موعد، وضعیت و شاخص راستی‌آزمایی اقدام را نگه می‌دارد.",
        helpEn: "Tracks owner, due date, state and verification metric for corrective work.",
        icon: BadgeCheck,
    },
    {
        key: "taxonomy",
        href: "/quality/taxonomy",
        fa: "طبقه‌بندی دلایل",
        en: "Reason taxonomy",
        helpFa: "دلیل خام مشتری حفظ می‌شود و دلیل استاندارد به‌صورت نسخه‌دار کنار آن قرار می‌گیرد.",
        helpEn: "Raw customer reason is preserved while normalized reasons are versioned.",
        icon: Tags,
    },
    {
        key: "dataQuality",
        href: "/quality/data-quality",
        fa: "کیفیت داده و ردیابی",
        en: "Data quality & traceability",
        helpFa: "پوشش اتصال محصول، بازرسی، پرونده و Lot/Batch دریافت را اندازه می‌گیرد و شکاف allocation تا سفارش را شفاف نشان می‌دهد.",
        helpEn: "Measures product, inspection, case and receiving lot/batch coverage and exposes the remaining allocation-to-order gap.",
        icon: Server,
    },
    {
        key: "metrics",
        href: "/quality/metrics",
        fa: "رجیستری شاخص‌ها",
        en: "Metric registry",
        helpFa: "تعریف، فرمول، واحد و مخرج هر شاخص کیفیت را شفاف می‌کند.",
        helpEn: "Makes each quality metric definition, formula, unit and denominator explicit.",
        icon: Activity,
    },
    {
        key: "governance",
        href: "/quality/governance",
        fa: "حاکمیت و ممیزی",
        en: "Governance & audit",
        helpFa: "مرز حقیقت و فرضیه، سیاست AI و رخدادهای ممیزی رسمی را نشان می‌دهد.",
        helpEn: "Shows truth boundaries, AI policy and canonical audit events.",
        icon: ShieldCheck,
    },
] as const;
