import { Exception } from "@adonisjs/core/exceptions";
import type { HttpContext } from "@adonisjs/core/http";
import { recordAudit } from "#services/admin_audit_log_service";
import { requireRecentIdentityStepUp } from "#services/identity/step_up";
import { phase20TrustRiskService } from "#services/phase20_trust_risk_service";
import { addFraudCaseNoteValidator, assignFraudCaseValidator, createFraudCaseValidator, createRiskModelValidator, createRiskModelVersionValidator, createSubjectControlValidator, evaluateRiskValidator, updateFraudCaseStatusValidator } from "#validators/admin/phase20_trust_risk_validator";
function id(value: unknown) { const parsed = Number(value); if (!Number.isSafeInteger(parsed) || parsed < 1) throw new Exception("Invalid identifier", { status: 422, code: "E_TRUST_ID" }); return parsed; }
function key(ctx: HttpContext) { const value = ctx.request.header("Idempotency-Key")?.trim(); return value ? value.slice(0, 180) : null; }

export default class TrustRiskController {
    overview() { return phase20TrustRiskService.overview(); }
    cases() { return phase20TrustRiskService.cases(); }
    signals() { return phase20TrustRiskService.signals(); }
    models() { return phase20TrustRiskService.models(); }
    health() { return phase20TrustRiskService.health(); }
    async evaluate(ctx: HttpContext) { const payload = await ctx.request.validateUsing(evaluateRiskValidator); const result = await phase20TrustRiskService.evaluate({ ...payload, idempotency_key: payload.idempotency_key ?? key(ctx) }); ctx.response.status(result.replayed ? 200 : 201); if (!result.replayed) await recordAudit({ ctx, action: "trust.risk.evaluate", entityKind: "fraud_risk_score", entityId: result.data.score.id, payload: { subject_type: payload.subject_type, subject_id: payload.subject_id, band: result.data.score.band } }); return result; }
    async createModel(ctx: HttpContext) { const payload = await ctx.request.validateUsing(createRiskModelValidator); const actor = await ctx.auth.authenticate(); const result = await phase20TrustRiskService.createModel(payload, actor); ctx.response.status(201); await recordAudit({ ctx, action: "trust.model.create", entityKind: "fraud_risk_model", entityId: result.data.id, payload: { model_id: payload.model_id } }); return result; }
    async createModelVersion(ctx: HttpContext) { const payload = await ctx.request.validateUsing(createRiskModelVersionValidator); const actor = await ctx.auth.authenticate(); const result = await phase20TrustRiskService.createModelVersion(id(ctx.params.id), payload, actor); ctx.response.status(201); await recordAudit({ ctx, action: "trust.model.version.create", entityKind: "fraud_risk_model_version", entityId: result.data.id, payload: { version: payload.version } }); return result; }
    async promoteChampion(ctx: HttpContext) { const actor = await ctx.auth.authenticate(); await requireRecentIdentityStepUp(Number(actor.id), "trust.model.promote"); const versionId = id(ctx.params.id); const result = await phase20TrustRiskService.promoteChampion(versionId, actor, key(ctx)); if (!result.replayed) await recordAudit({ ctx, action: "trust.model.promote_champion", entityKind: "fraud_risk_model_version", entityId: versionId, payload: {} }); return result; }
    async createCase(ctx: HttpContext) { const payload = await ctx.request.validateUsing(createFraudCaseValidator); const actor = await ctx.auth.authenticate(); const result = await phase20TrustRiskService.createCase(payload, actor); ctx.response.status(201); await recordAudit({ ctx, action: "trust.case.create", entityKind: "fraud_case", entityId: result.data.id, payload: { subject_type: payload.subject_type, subject_id: payload.subject_id } }); return result; }
    async assignCase(ctx: HttpContext) { const payload = await ctx.request.validateUsing(assignFraudCaseValidator); const actor = await ctx.auth.authenticate(); const caseId = id(ctx.params.id); const result = await phase20TrustRiskService.assignCase(caseId, payload.assignee_user_id ?? null, actor); await recordAudit({ ctx, action: "trust.case.assign", entityKind: "fraud_case", entityId: caseId, payload: { assignee_user_id: payload.assignee_user_id ?? null } }); return result; }
    async updateCaseStatus(ctx: HttpContext) { const payload = await ctx.request.validateUsing(updateFraudCaseStatusValidator); const actor = await ctx.auth.authenticate(); const caseId = id(ctx.params.id); if (["resolved", "closed"].includes(payload.status)) await requireRecentIdentityStepUp(Number(actor.id), "trust.case.resolve"); const result = await phase20TrustRiskService.updateCaseStatus(caseId, payload, actor); await recordAudit({ ctx, action: `trust.case.${payload.status}`, entityKind: "fraud_case", entityId: caseId, payload: {} }); return result; }
    async addCaseNote(ctx: HttpContext) { const payload = await ctx.request.validateUsing(addFraudCaseNoteValidator); const actor = await ctx.auth.authenticate(); const caseId = id(ctx.params.id); const result = await phase20TrustRiskService.addCaseNote(caseId, payload.note, actor); await recordAudit({ ctx, action: "trust.case.note", entityKind: "fraud_case", entityId: caseId, payload: { note_length: payload.note.length } }); return result; }
    async createControl(ctx: HttpContext) { const payload = await ctx.request.validateUsing(createSubjectControlValidator); const actor = await ctx.auth.authenticate(); if (["block", "allow_override"].includes(payload.control)) await requireRecentIdentityStepUp(Number(actor.id), "trust.subject.control"); const result = await phase20TrustRiskService.createControl(payload, actor, key(ctx)); ctx.response.status(result.replayed ? 200 : 201); if (!result.replayed) await recordAudit({ ctx, action: `trust.control.${payload.control}`, entityKind: "fraud_subject_control", entityId: result.data.id, payload: { subject_type: payload.subject_type, subject_id: payload.subject_id } }); return result; }
    async releaseControl(ctx: HttpContext) { const actor = await ctx.auth.authenticate(); await requireRecentIdentityStepUp(Number(actor.id), "trust.subject.control"); const controlId = id(ctx.params.id); const result = await phase20TrustRiskService.releaseControl(controlId, actor, key(ctx)); if (!result.replayed) await recordAudit({ ctx, action: "trust.control.release", entityKind: "fraud_subject_control", entityId: controlId, payload: {} }); return result; }
    async blockSubject(ctx: HttpContext) { const actor = await ctx.auth.authenticate(); await requireRecentIdentityStepUp(Number(actor.id), "trust.subject.control"); const payload = await ctx.request.validateUsing(createSubjectControlValidator); const result = await phase20TrustRiskService.createControl({ ...payload, control: "block" }, actor, key(ctx)); if (!result.replayed) await recordAudit({ ctx, action: "trust.control.block", entityKind: "fraud_subject_control", entityId: result.data.id, payload: { subject_type: payload.subject_type, subject_id: payload.subject_id } }); return result; }
}
