"use client";
import type { Locale } from "@calibra/shared/i18n";
import { StatusBadge } from "#/components/StatusBadge";
import { Card, CardContent, CardHeader, CardTitle } from "#/components/ui/card";
import { formatNumber } from "#/lib/format";
import { usePlanningHealth } from "#/lib/queries/planning";
import { AsyncState, InfoLabel, MetricCard, statusFa } from "./planning-shared";

export function HealthSection({ locale }: { locale: Locale }) {
    const query = usePlanningHealth(); if (query.isPending || query.isError) return <AsyncState pending={query.isPending} error={query.isError} onRetry={() => void query.refetch()} />; const data = query.data.data;
    return <div className="flex flex-col gap-4"><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><MetricCard title="ردیف‌های مشاهده‌شده" help="تعداد order lineهای processing/completed در پنجره دادهٔ سلامت؛ این KPI فروش مشاهده‌شده است، نه Demand پنهان." value={formatNumber(data.observed_rows, locale)} note={`${formatNumber(data.source_window_days, locale)} روز اخیر`} tone="info" /><MetricCard title="Series مشاهده‌شده" help="تعداد Product/Variant series متمایز در دادهٔ ورودی. Series کم‌تاریخ در Run با quality جدا می‌شود." value={formatNumber(data.observed_series, locale)} note="ورودی قابل مشاهده Forecast" /><MetricCard title="Inventory مدیریت‌شده" help="تعداد inventory_items که manage_stock=true دارند؛ Planning موجودی جدیدی ایجاد نمی‌کند." value={formatNumber(data.managed_inventory_items, locale)} note="از Inventory canonical" /><MetricCard title="وضعیت موتور" help="اگر Run ناموفق باشد degraded است؛ نبود Run با not_configured گزارش می‌شود و به‌عنوان سالم جعل نمی‌شود." value={statusFa(data.state)} note={data.latest_run ? `${data.latest_run.model_code} · v${data.latest_run.model_version}` : "Run موجود نیست"} tone={data.state === "degraded" ? "danger" : data.state === "ready" ? "success" : "neutral"} /></section><Card><CardHeader><CardTitle className="text-base"><InfoLabel help="این بخش مرز قابلیت‌ها و کمبودهای واقعی سیستم را شفاف می‌کند تا اپراتور «Connected» یا «AI-ready» جعلی نبیند.">پوشش و محدودیت‌های فعلی</InfoLabel></CardTitle></CardHeader><CardContent className="grid gap-3 md:grid-cols-3"><HealthItem title="Stockout censoring" value={data.stockout_censoring === "partial" ? "پوشش جزئی" : data.stockout_censoring} help="فروش برابر تقاضا فرض نمی‌شود. در نسخه فعلی reconstruction تاریخی stockout کامل نیست و این محدودیت صریح گزارش می‌شود." /><HealthItem title="اقتصاد / COGS" value={data.economics === "not_connected_phase12" ? "در انتظار اتصال Phase 12" : data.economics} help="Phase 13 عدد اقتصادی authoritative تولید نمی‌کند. Contribution margin/COGS/working capital باید از Phase 12 بیاید." /><HealthItem title="Procurement" value={data.procurement === "planning_only_phase14" ? "فقط برنامه‌ریزی؛ اجرای خرید در Phase 14" : data.procurement} help="Replenishment recommendation می‌تواند ورودی Phase 14 باشد؛ این فاز Supplier/PO جعلی نمی‌سازد." /></CardContent></Card><Card><CardHeader><CardTitle className="text-base"><InfoLabel help="Registry واقعی مدل‌های قابل استفاده در Forecast. Production با نسخه صریح اجرا می‌شود و «latest» مبهم ندارد.">Model Registry</InfoLabel></CardTitle></CardHeader><CardContent className="space-y-2">{data.model_registry.map((model) => <div key={`${model.code}:${model.version}`} className="flex items-center justify-between rounded-lg border border-border px-3 py-2 text-sm"><div><span className="font-medium">{model.code}</span><span className="ms-2 text-muted-foreground text-xs">v{model.version}</span></div><StatusBadge tone="success">Baseline production</StatusBadge></div>)}</CardContent></Card></div>;
}
function HealthItem({ title, value, help }: { title: string; value: string; help: string }) { return <div className="rounded-xl border border-border p-4"><div className="text-muted-foreground text-xs"><InfoLabel help={help}>{title}</InfoLabel></div><div className="mt-2 font-medium text-sm">{value}</div></div>; }
