"use client";
import type { Locale } from "@calibra/shared/i18n";
import { useMemo, useState } from "react";
import { StatusBadge } from "#/components/StatusBadge";
import { Button } from "#/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "#/components/ui/card";
import { Input } from "#/components/ui/input";
import { formatDate, formatNumber } from "#/lib/format";
import { type PlanningOverride, useCreatePlanningOverride, usePlanningForecast, usePlanningOverrides, useReviewPlanningOverride } from "#/lib/queries/planning";
import { AsyncState, InfoLabel, statusFa, statusTone } from "./planning-shared";

export function OverridesSection({ locale }: { locale: Locale }) {
    const forecast = usePlanningForecast(); const overrides = usePlanningOverrides(); const create = useCreatePlanningOverride();
    const points = useMemo(() => forecast.data?.data.series.flatMap((series) => series.points.map((point) => ({ ...point, name: series.name, sku: series.sku }))) ?? [], [forecast.data]);
    const [pointId, setPointId] = useState(""); const selected = points.find((point) => point.id === Number(pointId)); const [quantity, setQuantity] = useState(""); const [reason, setReason] = useState("");
    if (forecast.isPending || overrides.isPending || forecast.isError || overrides.isError) return <AsyncState pending={forecast.isPending || overrides.isPending} error={forecast.isError || overrides.isError} onRetry={() => { void forecast.refetch(); void overrides.refetch(); }} />;
    return <div className="grid gap-4 xl:grid-cols-[0.85fr_1.15fr]"><Card><CardHeader><CardTitle className="text-base"><InfoLabel help="Override مقدار forecast point اصلی را حذف یا overwrite نمی‌کند؛ original و override هر دو immutable نگه داشته می‌شوند و review جداگانه دارند.">ثبت Override انسانی</InfoLabel></CardTitle></CardHeader><CardContent className="space-y-4"><label className="grid gap-1.5 text-xs"><span>Forecast Point ID</span><Input inputMode="numeric" value={pointId} onChange={(event) => { setPointId(event.target.value); const point = points.find((candidate) => candidate.id === Number(event.target.value)); setQuantity(point ? String(Math.round(point.point)) : ""); }} placeholder={points[0] ? String(points[0].id) : "—"} /></label>{selected ? <div className="rounded-lg bg-muted/50 p-3 text-xs"><div className="font-medium">{selected.name}</div><div className="mt-1 text-muted-foreground">{formatDate(selected.date, locale)} · مقدار اصلی {formatNumber(Math.round(selected.point), locale)}</div></div> : null}<label className="grid gap-1.5 text-xs"><span><InfoLabel help="مقدار پیشنهادی اپراتور است و تا زمان review صرفاً evidence برنامه‌ریزی محسوب می‌شود.">مقدار Override</InfoLabel></span><Input inputMode="decimal" value={quantity} onChange={(event) => setQuantity(event.target.value)} /></label><label className="grid gap-1.5 text-xs"><span>دلیل</span><Input value={reason} onChange={(event) => setReason(event.target.value)} placeholder="مثلاً کمپین تأییدشده یا محدودیت عملیاتی" /></label><Button type="button" disabled={!selected || reason.trim().length < 5} isLoading={create.isPending} onClick={() => create.mutate({ forecast_point_id: Number(pointId), override_quantity: Number(quantity), reason })}>ثبت برای بررسی</Button></CardContent></Card><Card><CardHeader><CardTitle className="text-base"><InfoLabel help="فهرست immutable درخواست‌های Override با وضعیت review. تأیید Override فعلاً فقط governance state را تغییر می‌دهد و Forecast point canonical را rewrite نمی‌کند.">صف بررسی Overrideها</InfoLabel></CardTitle></CardHeader><CardContent className="space-y-2">{overrides.data.data.length === 0 ? <p className="text-muted-foreground text-sm">Override ثبت نشده است.</p> : overrides.data.data.map((item) => <OverrideRow key={item.id} item={item} locale={locale} />)}</CardContent></Card></div>;
}
function OverrideRow({ item, locale }: { item: PlanningOverride; locale: Locale }) {
    const review = useReviewPlanningOverride(item.id);
    return <div className="rounded-xl border border-border p-3"><div className="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between"><div><div className="font-medium text-sm">{item.product_name}</div><div className="mt-1 text-muted-foreground text-xs">{item.forecast_date ? formatDate(item.forecast_date, locale) : "—"} · {formatNumber(Math.round(item.original_quantity), locale)} ← {formatNumber(Math.round(item.override_quantity), locale)}</div><div className="mt-2 text-xs">{item.reason}</div></div><StatusBadge tone={statusTone(item.status)}>{statusFa(item.status)}</StatusBadge></div>{item.status === "pending" ? <div className="mt-3 flex gap-2"><Button type="button" size="sm" isLoading={review.isPending} onClick={() => review.mutate({ decision: "approved" })}>تأیید</Button><Button type="button" size="sm" variant="outline" disabled={review.isPending} onClick={() => review.mutate({ decision: "rejected" })}>رد</Button></div> : null}</div>;
}
