"use client";
import type { Locale } from "@calibra/shared/i18n";
import { useState } from "react";
import { StatusBadge } from "#/components/StatusBadge";
import { Button } from "#/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "#/components/ui/card";
import { Input } from "#/components/ui/input";
import { WandSparkles } from "#/icons";
import { formatNumber, formatPercent } from "#/lib/format";
import { useCreatePlanningScenario, usePlanningScenarios } from "#/lib/queries/planning";
import { AsyncState, InfoLabel, statusFa, statusTone } from "./planning-shared";

export function ScenariosSection({ locale }: { locale: Locale }) {
    const query = usePlanningScenarios(); const create = useCreatePlanningScenario(); const [title, setTitle] = useState("سناریوی تقاضای بالا"); const [multiplier, setMultiplier] = useState("1.15"); const [leadTime, setLeadTime] = useState("0");
    if (query.isPending || query.isError) return <AsyncState pending={query.isPending} error={query.isError} onRetry={() => void query.refetch()} />;
    return <div className="grid gap-4 xl:grid-cols-[0.8fr_1.2fr]"><Card><CardHeader><CardTitle className="text-base"><InfoLabel help="Scenario فقط یک simulation versioned است. ساخت آن هیچ stock، price، order یا Purchase Order را تغییر نمی‌دهد.">سناریوی جدید</InfoLabel></CardTitle></CardHeader><CardContent className="space-y-4"><label className="grid gap-1.5 text-xs"><span>نام سناریو</span><Input value={title} onChange={(event) => setTitle(event.target.value)} /></label><label className="grid gap-1.5 text-xs"><span><InfoLabel help="ضریب ۱٫۱۵ یعنی pointهای baseline برای simulation به میزان ۱۵٪ افزایش می‌یابند. این پارامتر اثر واقعی کمپین را ادعا نمی‌کند.">ضریب تقاضا</InfoLabel></span><Input inputMode="decimal" value={multiplier} onChange={(event) => setMultiplier(event.target.value)} /></label><label className="grid gap-1.5 text-xs"><span><InfoLabel help="Lead time فعلاً assumption سناریو است؛ تا زمانی که Phase 14 Procurement authority کامل نشود، تأمین‌کننده یا PO جعلی ساخته نمی‌شود.">تأخیر تأمین (روز)</InfoLabel></span><Input inputMode="numeric" value={leadTime} onChange={(event) => setLeadTime(event.target.value)} /></label><Button type="button" isLoading={create.isPending} onClick={() => create.mutate({ title, demand_multiplier: Number(multiplier), lead_time_days: Number(leadTime) })}><WandSparkles className="size-4" aria-hidden="true" />ساخت Simulation</Button></CardContent></Card><Card><CardHeader><CardTitle className="text-base"><InfoLabel help="هر ردیف assumptionهای ذخیره‌شده و version را نشان می‌دهد. نتیجه سناریو در backend از Forecast پایه محاسبه می‌شود.">سناریوهای ذخیره‌شده</InfoLabel></CardTitle></CardHeader><CardContent className="space-y-2">{query.data.data.length === 0 ? <p className="text-muted-foreground text-sm">هنوز سناریویی ثبت نشده است.</p> : query.data.data.map((scenario) => <div key={scenario.id} className="flex flex-col gap-2 rounded-xl border border-border p-3 sm:flex-row sm:items-center sm:justify-between"><div><div className="font-medium text-sm">{scenario.title}</div><div className="mt-1 text-muted-foreground text-xs">ضریب {formatPercent((scenario.demand_multiplier - 1) * 100, locale, 0)} نسبت به مبنا · Lead time: {formatNumber(scenario.lead_time_days, locale)} روز</div></div><div className="flex items-center gap-2"><StatusBadge tone={statusTone(scenario.status)}>{statusFa(scenario.status)}</StatusBadge><span className="text-muted-foreground text-xs">v{formatNumber(scenario.version, locale)}</span></div></div>)}</CardContent></Card></div>;
}
