"use client";

import type { Locale } from "@calibra/shared/i18n";
import { AlertCircle, ArrowDownUp, CheckCircle2, Clock3, Copy, ExternalLink, RefreshCw, Search, ShieldCheck, WalletCards, XCircle } from "lucide-react";
import { useLocale } from "next-intl";
import { type ReactNode, useMemo, useState } from "react";
import { Button } from "#/components/ui/button";
import { Input } from "#/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "#/components/ui/select";
import { Sheet, SheetContent } from "#/components/ui/sheet";
import { Skeleton } from "#/components/ui/skeleton";
import { toast } from "#/components/ui/toast";
import { formatDateTime, formatMoney, formatNumber } from "#/lib/format";
import { Link } from "#/lib/i18n/navigation";
import { type AdminTransaction, type PaymentAttemptStatus, useTransaction, useTransactions, useTransactionSummary } from "#/lib/queries/transactions";
import type { TableViewFilter, TableViewQuery } from "#/lib/table-view";
import { cn } from "#/lib/utils";

const STATUSES: PaymentAttemptStatus[] = ["initiated", "awaiting_callback", "verified", "failed", "cancelled", "refunded"];
const GATEWAYS = ["zarinpal", "mellat", "sadad", "parsian", "idpay", "nextpay", "payir", "zibal", "digipay", "snapppay", "azkivam", "bitpay", "card_to_card", "cod", "bank_transfer"];
const C = {
 fa:{title:"تراکنش‌ها",subtitle:"مرکز کنترل پرداخت‌ها، خطاها و بازپرداخت‌های فروشگاه",search:"جستجو با شناسه تراکنش، سفارش، Authority یا Ref ID…",all:"همه وضعیت‌ها",gateways:"همه درگاه‌ها",newest:"جدیدترین",oldest:"قدیمی‌ترین",highest:"بیشترین مبلغ",lowest:"کمترین مبلغ",refresh:"بروزرسانی",total:"کل تراکنش‌ها",verified:"پرداخت موفق",pending:"در انتظار نتیجه",attention:"نیازمند بررسی",amount:"مبلغ",transaction:"تراکنش",order:"سفارش",gateway:"درگاه",status:"وضعیت",time:"زمان",reference:"شناسه مرجع",empty:"تراکنشی با این فیلترها پیدا نشد",emptyHint:"فیلترها را تغییر دهید یا شناسه دیگری جستجو کنید.",error:"دریافت تراکنش‌ها با خطا مواجه شد.",retry:"تلاش مجدد",previous:"قبلی",next:"بعدی",details:"جزئیات تراکنش",flow:"چرخه پرداخت",initiated:"ایجاد درخواست",verifiedAt:"تأیید نهایی",identifiers:"شناسه‌ها",attempt:"Attempt ID",authority:"Authority",ref:"Transaction / Ref ID",gatewayError:"خطای درگاه",payload:"پاسخ ثبت‌شده درگاه",openOrder:"مشاهده سفارش",live:"داده زنده از بک‌اند"},
 en:{title:"Transactions",subtitle:"Payment operations, failures and refund control center",search:"Search transaction, order, authority or reference ID…",all:"All statuses",gateways:"All gateways",newest:"Newest",oldest:"Oldest",highest:"Highest amount",lowest:"Lowest amount",refresh:"Refresh",total:"All transactions",verified:"Verified payments",pending:"Awaiting result",attention:"Needs attention",amount:"Amount",transaction:"Transaction",order:"Order",gateway:"Gateway",status:"Status",time:"Time",reference:"Reference",empty:"No transactions match these filters",emptyHint:"Change filters or search for another identifier.",error:"Transactions could not be loaded.",retry:"Retry",previous:"Previous",next:"Next",details:"Transaction details",flow:"Payment lifecycle",initiated:"Request initiated",verifiedAt:"Final verification",identifiers:"Identifiers",attempt:"Attempt ID",authority:"Authority",ref:"Transaction / Ref ID",gatewayError:"Gateway error",payload:"Recorded gateway response",openOrder:"Open order",live:"Live backend data"}
} as const;
const SL:Record<PaymentAttemptStatus,{fa:string;en:string}>={initiated:{fa:"شروع‌شده",en:"Initiated"},awaiting_callback:{fa:"در انتظار درگاه",en:"Awaiting gateway"},verified:{fa:"موفق",en:"Verified"},failed:{fa:"ناموفق",en:"Failed"},cancelled:{fa:"لغوشده",en:"Cancelled"},refunded:{fa:"بازپرداخت",en:"Refunded"}};
function tone(s:PaymentAttemptStatus){if(s==="verified")return"border-emerald-200 bg-emerald-50 text-emerald-700 dark:border-emerald-900 dark:bg-emerald-950/40 dark:text-emerald-300";if(s==="failed"||s==="cancelled")return"border-red-200 bg-red-50 text-red-700 dark:border-red-900 dark:bg-red-950/40 dark:text-red-300";if(s==="refunded")return"border-violet-200 bg-violet-50 text-violet-700 dark:border-violet-900 dark:bg-violet-950/40 dark:text-violet-300";return"border-amber-200 bg-amber-50 text-amber-700 dark:border-amber-900 dark:bg-amber-950/40 dark:text-amber-300"}
function Pill({s,locale}:{s:PaymentAttemptStatus;locale:Locale}){const l=locale==="fa"?"fa":"en";return <span className={cn("inline-flex rounded-full border px-2.5 py-1 font-medium text-xs",tone(s))}>{SL[s][l]}</span>}
function copy(v:string|number|null){if(v===null)return;void navigator.clipboard.writeText(String(v));toast.success("Copied")}

export function TransactionsCenter(){
 const locale=useLocale() as Locale,l=locale==="fa"?"fa":"en",t=C[l];
 const [page,setPage]=useState(1),[q,setQ]=useState(""),[status,setStatus]=useState("all"),[gateway,setGateway]=useState("all"),[sort,setSort]=useState("newest"),[selected,setSelected]=useState<number|null>(null);
 const query=useMemo<TableViewQuery>(()=>{const filter:TableViewFilter[]=[];if(status!=="all")filter.push({field:"status",op:"eq",value:status});if(gateway!=="all")filter.push({field:"gateway_code_snapshot",op:"eq",value:gateway});const sorts:Record<string,TableViewQuery["sort"]>={newest:[{field:"created_at",dir:"desc"}],oldest:[{field:"created_at",dir:"asc"}],highest:[{field:"amount_minor",dir:"desc"}],lowest:[{field:"amount_minor",dir:"asc"}]};return{page,limit:25,filter,filterOr:[],sort:sorts[sort]??sorts.newest}},[page,status,gateway,sort]);
 const list=useTransactions(query,q),summary=useTransactionSummary(),detail=useTransaction(selected);const rows=list.data?.data??[],meta=list.data?.meta??{page,limit:25,total:0,lastPage:1},stats=summary.data;const pending=(stats?.by_status.initiated?.count??0)+(stats?.by_status.awaiting_callback?.count??0),attention=(stats?.by_status.failed?.count??0)+(stats?.by_status.cancelled?.count??0);
 return <div className="mx-auto w-full max-w-[1600px] space-y-5 p-4 sm:p-6 lg:p-8">
  <header className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><div className="mb-1 flex items-center gap-2 text-muted-foreground text-xs"><ShieldCheck className="size-3.5"/>{t.live}</div><h1 className="font-bold text-2xl tracking-tight sm:text-3xl">{t.title}</h1><p className="mt-1 text-muted-foreground text-sm">{t.subtitle}</p></div><Button variant="outline" onClick={()=>{void list.refetch();void summary.refetch()}} disabled={list.isFetching}><RefreshCw className={cn("me-2 size-4",list.isFetching&&"animate-spin")}/>{t.refresh}</Button></header>
  <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={WalletCards} label={t.total} value={stats?formatNumber(stats.total_count,locale):"—"} hint={stats?formatMoney(stats.total_amount_minor,locale):"—"}/><Metric icon={CheckCircle2} label={t.verified} value={stats?formatNumber(stats.by_status.verified?.count??0,locale):"—"} hint={stats?formatMoney(stats.by_status.verified?.amount_minor??0,locale):"—"} tone="good"/><Metric icon={Clock3} label={t.pending} value={stats?formatNumber(pending,locale):"—"} hint="" tone="warn"/><Metric icon={AlertCircle} label={t.attention} value={stats?formatNumber(attention,locale):"—"} hint="" tone={attention>0?"bad":"good"}/></div>
  <section className="overflow-hidden rounded-xl border bg-card shadow-sm"><div className="flex flex-col gap-3 border-b p-3 lg:flex-row lg:items-center"><div className="relative flex-1"><Search className="absolute start-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><Input value={q} onChange={e=>{setQ(e.target.value);setPage(1)}} placeholder={t.search} className="ps-9"/></div><div className="grid grid-cols-2 gap-2 sm:flex"><Select value={status} onValueChange={v=>{setStatus(v);setPage(1)}}><SelectTrigger className="sm:w-[170px]"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">{t.all}</SelectItem>{STATUSES.map(s=><SelectItem key={s} value={s}>{SL[s][l]}</SelectItem>)}</SelectContent></Select><Select value={gateway} onValueChange={v=>{setGateway(v);setPage(1)}}><SelectTrigger className="sm:w-[170px]"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">{t.gateways}</SelectItem>{GATEWAYS.map(g=><SelectItem key={g} value={g}>{g}</SelectItem>)}</SelectContent></Select><Select value={sort} onValueChange={v=>{setSort(v);setPage(1)}}><SelectTrigger className="col-span-2 sm:w-[170px]"><ArrowDownUp className="me-2 size-3.5"/><SelectValue/></SelectTrigger><SelectContent><SelectItem value="newest">{t.newest}</SelectItem><SelectItem value="oldest">{t.oldest}</SelectItem><SelectItem value="highest">{t.highest}</SelectItem><SelectItem value="lowest">{t.lowest}</SelectItem></SelectContent></Select></div></div>
  {list.isPending?<div className="space-y-2 p-4">{Array.from({length:8}).map((_,i)=><Skeleton key={i} className="h-12 w-full"/>)}</div>:list.isError?<Empty icon={XCircle} title={t.error} subtitle="" action={<Button variant="outline" onClick={()=>void list.refetch()}>{t.retry}</Button>}/>:rows.length===0?<Empty icon={Search} title={t.empty} subtitle={t.emptyHint}/>:<><div className="overflow-x-auto"><table className="w-full min-w-[920px] text-sm"><thead className="bg-muted/45 text-muted-foreground"><tr className="border-b">{[t.transaction,t.order,t.gateway,t.status,t.amount,t.reference,t.time].map(x=><th key={x} className="px-4 py-3 text-start font-medium text-xs">{x}</th>)}</tr></thead><tbody>{rows.map(r=><Row key={r.id} row={r} locale={locale} onOpen={()=>setSelected(r.id)}/>)}</tbody></table></div><footer className="flex items-center justify-between gap-3 border-t px-4 py-3 text-sm"><span className="text-muted-foreground">{formatNumber(meta.total,locale)} {t.total}</span><div className="flex items-center gap-2"><Button size="sm" variant="outline" disabled={page<=1} onClick={()=>setPage(p=>Math.max(1,p-1))}>{t.previous}</Button><span className="text-muted-foreground">{formatNumber(page,locale)} / {formatNumber(meta.lastPage,locale)}</span><Button size="sm" variant="outline" disabled={page>=meta.lastPage} onClick={()=>setPage(p=>p+1)}>{t.next}</Button></div></footer></>}
  </section><Drawer id={selected} open={selected!==null} onOpenChange={o=>{if(!o)setSelected(null)}} locale={locale} t={t} detail={detail}/>
 </div>
}
function Metric({icon:Icon,label,value,hint,tone="neutral"}:{icon:typeof WalletCards;label:string;value:string;hint:string;tone?:"neutral"|"good"|"warn"|"bad"}){const tc=tone==="good"?"bg-emerald-500/10 text-emerald-600":tone==="warn"?"bg-amber-500/10 text-amber-600":tone==="bad"?"bg-red-500/10 text-red-600":"bg-primary/10 text-primary";return <div className="rounded-xl border bg-card p-4 shadow-sm"><div className="flex justify-between gap-3"><div><p className="text-muted-foreground text-xs">{label}</p><p className="mt-2 font-bold text-2xl tabular-nums">{value}</p><p className="mt-1 text-muted-foreground text-xs">{hint}</p></div><div className={cn("grid size-9 place-items-center rounded-lg",tc)}><Icon className="size-4"/></div></div></div>}
function Row({row,locale,onOpen}:{row:AdminTransaction;locale:Locale;onOpen:()=>void}){return <tr className="cursor-pointer border-b transition-colors last:border-0 hover:bg-muted/35" onClick={onOpen}><td className="px-4 py-3 font-semibold">#{formatNumber(row.id,locale)}</td><td className="px-4 py-3"><Link href={`/orders/${row.order_id}` as never} onClick={e=>e.stopPropagation()} className="inline-flex items-center gap-1 font-medium hover:text-primary hover:underline">#{formatNumber(row.order_id,locale)}<ExternalLink className="size-3"/></Link></td><td className="px-4 py-3"><span className="rounded-md bg-muted px-2 py-1 font-medium text-xs">{row.gateway_code}</span></td><td className="px-4 py-3"><Pill s={row.status} locale={locale}/></td><td className="whitespace-nowrap px-4 py-3 font-semibold tabular-nums">{formatMoney(row.amount_minor,locale)}</td><td className="max-w-[180px] truncate px-4 py-3 font-mono text-muted-foreground text-xs">{row.gateway_transaction_id??row.gateway_authority??"—"}</td><td className="whitespace-nowrap px-4 py-3 text-muted-foreground text-xs">{row.created_at?formatDateTime(row.created_at,locale):"—"}</td></tr>}
function Empty({icon:Icon,title,subtitle,action}:{icon:typeof Search;title:string;subtitle:string;action?:ReactNode}){return <div className="grid min-h-72 place-items-center p-8 text-center"><div><div className="mx-auto mb-3 grid size-11 place-items-center rounded-full bg-muted"><Icon className="size-5 text-muted-foreground"/></div><p className="font-medium">{title}</p>{subtitle?<p className="mt-1 text-muted-foreground text-sm">{subtitle}</p>:null}{action?<div className="mt-4">{action}</div>:null}</div></div>}
function Drawer({id,open,onOpenChange,locale,t,detail}:{id:number|null;open:boolean;onOpenChange:(o:boolean)=>void;locale:Locale;t:typeof C.fa|typeof C.en;detail:ReturnType<typeof useTransaction>}){const r=detail.data;return <Sheet open={open} onOpenChange={onOpenChange}><SheetContent className="w-full overflow-y-auto p-0 sm:max-w-xl"><div className="border-b p-5"><p className="text-muted-foreground text-xs">{t.details}</p><div className="mt-1 flex items-center justify-between"><h2 className="font-bold text-xl">#{id?formatNumber(id,locale):"—"}</h2>{r?<Pill s={r.status} locale={locale}/>:null}</div></div>{detail.isPending?<div className="space-y-3 p-5"><Skeleton className="h-24"/><Skeleton className="h-40"/></div>:r?<div className="space-y-5 p-5"><div className="rounded-xl border bg-muted/20 p-4"><p className="text-muted-foreground text-xs">{t.amount}</p><p className="mt-1 font-bold text-2xl">{formatMoney(r.amount_minor,locale)}</p><div className="mt-3 flex justify-between text-sm"><span className="text-muted-foreground">{t.gateway}</span><span>{r.gateway_code}</span></div></div><section><h3 className="mb-3 font-semibold text-sm">{t.flow}</h3><div className="ms-2 space-y-5 border-s ps-5"><Timeline icon={Clock3} label={t.initiated} value={r.initiated_at??r.created_at} locale={locale}/><Timeline icon={r.status==="verified"?CheckCircle2:AlertCircle} label={t.verifiedAt} value={r.verified_at} locale={locale}/></div></section><section><h3 className="mb-2 font-semibold text-sm">{t.identifiers}</h3><div className="divide-y rounded-xl border"><Id label={t.attempt} value={r.id}/><Id label={t.authority} value={r.gateway_authority}/><Id label={t.ref} value={r.gateway_transaction_id}/></div></section>{r.error_code||r.error_message?<div className="rounded-xl border border-red-200 bg-red-50 p-4 text-red-700 dark:border-red-900 dark:bg-red-950/30 dark:text-red-300"><p className="font-semibold text-sm">{t.gatewayError}{r.error_code?` · ${r.error_code}`:""}</p><p className="mt-1 text-xs">{r.error_message??"—"}</p></div>:null}<section><h3 className="mb-2 font-semibold text-sm">{t.payload}</h3><pre className="max-h-64 overflow-auto rounded-xl border bg-muted/35 p-3 text-[11px] leading-5" dir="ltr">{JSON.stringify(r.gateway_payload??{},null,2)}</pre></section><Button asChild className="w-full"><Link href={`/orders/${r.order_id}` as never}>{t.openOrder}<ExternalLink className="ms-2 size-4"/></Link></Button></div>:<Empty icon={XCircle} title={t.error} subtitle=""/>}</SheetContent></Sheet>}
function Timeline({icon:Icon,label,value,locale}:{icon:typeof Clock3;label:string;value:string|null;locale:Locale}){return <div className="relative"><div className="absolute -start-[2.05rem] grid size-6 place-items-center rounded-full border bg-background"><Icon className="size-3"/></div><p className="font-medium text-sm">{label}</p><p className="text-muted-foreground text-xs">{value?formatDateTime(value,locale):"—"}</p></div>}
function Id({label,value}:{label:string;value:string|number|null}){return <div className="flex items-center justify-between gap-3 px-3 py-2.5"><div className="min-w-0"><p className="text-muted-foreground text-[11px]">{label}</p><p className="truncate font-mono text-xs" dir="ltr">{value??"—"}</p></div>{value!==null?<Button variant="ghost" size="icon" className="size-8" onClick={()=>copy(value)}><Copy className="size-3.5"/></Button>:null}</div>}
