import { existsSync } from "node:fs";
import { readFile } from "node:fs/promises";
import { join } from "node:path";
import type { Command } from "commander";

import { buildComposeOptions } from "../core/compose-assembly";
import { SPIN_ENV_HEADER_MARKER } from "../core/env-render";
import { printHandoffCard } from "../core/handoff";
import { loadOrInitLocalMeta } from "../core/meta";
import { runPipeline } from "../core/pipeline";
import { pipelineSteps } from "../core/pipeline-steps";
import { LOCAL_SLUG } from "../core/slug";

import { runDoctor } from "./doctor";
import { printStartHeader } from "./start";
import { runStop } from "./stop";

/** Legacy header marker, still honored so a stack provisioned by the old spin isn't clobbered. */
const LEGACY_ENV_MARKER = "Generated by scripts/spin.mjs";

/**
 * `spin local [action]` — the full prod-parity stack against the **current checkout**: no worktree,
 * no branch, no PR. For operators who want everything running locally, and for agents on a branch
 * they're already on. The slug is fixed to `local`, so one machine has at most one in-place spin.
 */
async function localStart(opts: { withWeb?: boolean }): Promise<void> {
    const meta = await loadOrInitLocalMeta();

    /** Guard: refuse to clobber an `apps/api/.env` that spin didn't generate. */
    const apiEnvPath = join(meta.worktreePath, "apps/api/.env");
    if (existsSync(apiEnvPath)) {
        const head = (await readFile(apiEnvPath, "utf8")).split("\n", 1)[0] ?? "";
        if (!head.includes(SPIN_ENV_HEADER_MARKER) && !head.includes(LEGACY_ENV_MARKER)) {
            throw new Error(
                [
                    "apps/api/.env exists and was not generated by spin (no header line).",
                    "Move it aside (`mv apps/api/.env apps/api/.env.before-spin`) or delete it, then re-run.",
                    "spin owns the .env when it provisions a stack — silently overwriting custom values would be a footgun.",
                ].join("\n  "),
            );
        }
    }

    printStartHeader(meta, "in-place (no worktree, no branch, no PR)");
    await runPipeline(pipelineSteps(), {
        meta,
        compose: buildComposeOptions(meta),
        worktree: false,
        withWeb: Boolean(opts.withWeb),
        noPr: true,
    });
    printHandoffCard(meta, { withWeb: Boolean(opts.withWeb) });
}

export function registerLocal(program: Command): void {
    program
        .command("local")
        .argument("[action]", "start | stop | status | doctor", "start")
        .description("bring up the full stack against the current checkout (in-place, no worktree/PR)")
        .option("--with-web", "also start the storefront (web)")
        .option("--purge", "on stop: also drop docker volumes")
        .option("--json", "on status/doctor: machine-readable output")
        .allowExcessArguments(true)
        .action(async (action: string, opts: { withWeb?: boolean; purge?: boolean; json?: boolean }) => {
            if (action === "start" || action === "up" || action === "bootstrap") {
                await localStart(opts);
            } else if (action === "stop" || action === "down") {
                /** Never remove the worktree for `local` — it's the main checkout. */
                await runStop(LOCAL_SLUG, { purge: Boolean(opts.purge), remove: false, force: false });
            } else if (action === "status" || action === "doctor") {
                await runDoctor(LOCAL_SLUG, { json: Boolean(opts.json) });
            } else {
                await localStart(opts);
            }
        });
}
