import type { Locale } from "@calibra/shared/i18n";

import type { TicketPriority, TicketStatus } from "./types";

const FA = {
    operations: "عملیات پشتیبانی",
    center: "مرکز تیکت‌ها",
    centerSubtitle: "مدیریت صف پاسخ‌گویی، SLA، ارجاع، گفت‌وگو و تاریخچه عملیاتی در یک نمای یکپارچه",
    settings: "تنظیمات SLA",
    newTicket: "تیکت جدید",
    createTicket: "ایجاد تیکت",
    linkedCustomer: "مشتری متصل",
    noCustomer: "بدون اتصال به مشتری",
    assignee: "مسئول",
    defaultAssignment: "ارجاع پیش‌فرض",
    unassigned: "بدون مسئول",
    requesterName: "نام درخواست‌کننده",
    email: "ایمیل",
    phone: "تلفن",
    categoryPlaceholder: "دسته تیکت؛ مانند پرداخت یا ارسال",
    subject: "موضوع تیکت",
    initialMessage: "شرح درخواست یا اولین پیام",
    cancel: "انصراف",
    creating: "در حال ثبت…",
    create: "ثبت تیکت",
    resourceWarning: "فهرست مشتری یا مدیر کامل بارگذاری نشد؛ ثبت دستی تیکت همچنان ممکن است.",
    createFailed: "ثبت تیکت ناموفق بود. ورودی‌ها و اتصال API را بررسی کنید.",
    activeTickets: "تیکت‌های فعال",
    waitingCustomer: "در انتظار مشتری",
    slaBreached: "نقض SLA",
    resolved30d: "حل‌شده در ۳۰ روز",
    avgFirstResponse: "میانگین پاسخ اول",
    minute: "دقیقه",
    trendTitle: "روند تیکت‌ها در ۳۰ روز گذشته",
    trendSubtitle: "ستون اصلی: ایجاد شده · ستون دوم: حل‌شده",
    recentQueue: "آخرین فعالیت صف",
    emptyQueue: "صف تیکت خالی است.",
    search: "جستجو در شماره، موضوع، نام، ایمیل یا تلفن",
    allStatuses: "همه وضعیت‌ها",
    allPriorities: "همه اولویت‌ها",
    allSla: "همه SLAها",
    healthySla: "در محدوده SLA",
    breachedSla: "SLA نقض‌شده",
    noResults: "تیکتی با این فیلترها پیدا نشد.",
    requester: "درخواست‌کننده",
    status: "وضعیت",
    priority: "اولویت",
    lastActivity: "آخرین فعالیت",
    previous: "قبلی",
    next: "بعدی",
    back: "بازگشت به مرکز تیکت‌ها",
    noContact: "بدون اطلاعات تماس",
    refresh: "به‌روزرسانی",
    conversation: "گفت‌وگو",
    requesterMessage: "پیام درخواست‌کننده",
    internalNote: "یادداشت داخلی",
    operatorReply: "پاسخ اپراتور",
    system: "سیستم",
    noMessages: "هنوز پیامی ثبت نشده است.",
    addResponse: "ثبت پاسخ",
    publicReply: "پاسخ عمومی",
    replyPlaceholder: "پاسخ به درخواست‌کننده…",
    notePlaceholder: "یادداشتی که فقط اپراتورها می‌بینند…",
    ticketVersion: "نسخه تیکت",
    saving: "در حال ثبت…",
    addMessage: "ثبت پیام",
    messageFailed: "ثبت پیام ناموفق بود؛ ممکن است تیکت هم‌زمان تغییر کرده باشد.",
    controls: "کنترل تیکت",
    syncing: "در حال همگام‌سازی تغییرات…",
    changeFailed: "ذخیره تغییر ناموفق بود. اطلاعات تیکت را به‌روزرسانی کنید.",
    firstResponse: "پاسخ اول",
    resolution: "حل تیکت",
    completed: "انجام‌شده",
    noSla: "بدون SLA",
    onTrack: "در محدوده",
    responseDeadline: "مهلت پاسخ",
    resolutionDeadline: "مهلت حل",
    created: "ایجاد",
    context: "زمینه تیکت",
    channel: "کانال",
    category: "دسته",
    viewCustomer: "مشاهده مشتری متصل",
    noLinkedCustomer: "این تیکت به پروفایل مشتری متصل نیست.",
    history: "تاریخچه عملیات",
    loadFailed: "دریافت تیکت ناموفق بود",
    retry: "تلاش دوباره",
    settingsTitle: "تنظیمات تیکت",
    settingsSubtitle: "شماره‌گذاری، SLA و ارجاع پیش‌فرض صف پشتیبانی این فروشگاه",
    responsePolicy: "سیاست پاسخ‌گویی",
    referencePrefix: "پیشوند شماره تیکت",
    defaultPriority: "اولویت پیش‌فرض",
    firstResponseMinutes: "مهلت پاسخ اول (دقیقه)",
    resolutionMinutes: "مهلت حل تیکت (دقیقه)",
    defaultAssignee: "مسئول پیش‌فرض",
    noDefaultAssignee: "بدون مسئول پیش‌فرض",
    searchAdmin: "جستجوی مدیر…",
    noAdmin: "مدیری پیدا نشد.",
    clearDefaultAssignee: "حذف ارجاع پیش‌فرض",
    saveSettings: "ذخیره تنظیمات",
    settingsSaved: "تنظیمات ذخیره شد.",
    settingsFailed: "ذخیره تنظیمات ناموفق بود.",
} as const;

const EN: Record<keyof typeof FA, string> = {
    operations: "Support operations",
    center: "Ticket center",
    centerSubtitle: "Manage the support queue, SLA, assignment, conversations, and operational history in one workspace",
    settings: "SLA settings",
    newTicket: "New ticket",
    createTicket: "Create ticket",
    linkedCustomer: "Linked customer",
    noCustomer: "No linked customer",
    assignee: "Assignee",
    defaultAssignment: "Use default assignment",
    unassigned: "Unassigned",
    requesterName: "Requester name",
    email: "Email",
    phone: "Phone",
    categoryPlaceholder: "Ticket category, e.g. payment or shipping",
    subject: "Ticket subject",
    initialMessage: "Request details or initial message",
    cancel: "Cancel",
    creating: "Creating…",
    create: "Create ticket",
    resourceWarning: "Customer or admin options could not be fully loaded; manual ticket creation is still available.",
    createFailed: "Ticket creation failed. Check the inputs and API connection.",
    activeTickets: "Active tickets",
    waitingCustomer: "Waiting for customer",
    slaBreached: "SLA breaches",
    resolved30d: "Resolved in 30 days",
    avgFirstResponse: "Average first response",
    minute: "min",
    trendTitle: "Ticket trend over the last 30 days",
    trendSubtitle: "Primary bar: opened · Secondary bar: resolved",
    recentQueue: "Recent queue activity",
    emptyQueue: "The ticket queue is empty.",
    search: "Search reference, subject, name, email, or phone",
    allStatuses: "All statuses",
    allPriorities: "All priorities",
    allSla: "All SLA states",
    healthySla: "Within SLA",
    breachedSla: "SLA breached",
    noResults: "No tickets match these filters.",
    requester: "Requester",
    status: "Status",
    priority: "Priority",
    lastActivity: "Last activity",
    previous: "Previous",
    next: "Next",
    back: "Back to ticket center",
    noContact: "No contact details",
    refresh: "Refresh",
    conversation: "Conversation",
    requesterMessage: "Requester message",
    internalNote: "Internal note",
    operatorReply: "Operator reply",
    system: "System",
    noMessages: "No messages have been recorded yet.",
    addResponse: "Add response",
    publicReply: "Public reply",
    replyPlaceholder: "Reply to the requester…",
    notePlaceholder: "Note visible only to operators…",
    ticketVersion: "Ticket version",
    saving: "Saving…",
    addMessage: "Add message",
    messageFailed: "Could not add the message; the ticket may have changed concurrently.",
    controls: "Ticket controls",
    syncing: "Syncing changes…",
    changeFailed: "Could not save the change. Refresh the ticket and retry.",
    firstResponse: "First response",
    resolution: "Resolution",
    completed: "Completed",
    noSla: "No SLA",
    onTrack: "On track",
    responseDeadline: "Response deadline",
    resolutionDeadline: "Resolution deadline",
    created: "Created",
    context: "Ticket context",
    channel: "Channel",
    category: "Category",
    viewCustomer: "View linked customer",
    noLinkedCustomer: "This ticket is not linked to a customer profile.",
    history: "Operational history",
    loadFailed: "Could not load the ticket",
    retry: "Try again",
    settingsTitle: "Ticket settings",
    settingsSubtitle: "Numbering, SLA, and default assignment for this store's support queue",
    responsePolicy: "Response policy",
    referencePrefix: "Ticket reference prefix",
    defaultPriority: "Default priority",
    firstResponseMinutes: "First response target (minutes)",
    resolutionMinutes: "Resolution target (minutes)",
    defaultAssignee: "Default assignee",
    noDefaultAssignee: "No default assignee",
    searchAdmin: "Search admins…",
    noAdmin: "No admin found.",
    clearDefaultAssignee: "Clear default assignment",
    saveSettings: "Save settings",
    settingsSaved: "Settings saved.",
    settingsFailed: "Could not save settings.",
};

const STATUS_FA: Record<TicketStatus, string> = { open: "باز", pending: "در حال پیگیری", waiting_customer: "در انتظار مشتری", resolved: "حل‌شده", closed: "بسته" };
const STATUS_EN: Record<TicketStatus, string> = { open: "Open", pending: "In progress", waiting_customer: "Waiting for customer", resolved: "Resolved", closed: "Closed" };
const PRIORITY_FA: Record<TicketPriority, string> = { low: "کم", normal: "عادی", high: "بالا", urgent: "فوری" };
const PRIORITY_EN: Record<TicketPriority, string> = { low: "Low", normal: "Normal", high: "High", urgent: "Urgent" };

export function ticketCopy(locale: Locale) {
    return locale === "en"
        ? { text: EN, statuses: STATUS_EN, priorities: PRIORITY_EN }
        : { text: FA, statuses: STATUS_FA, priorities: PRIORITY_FA };
}
