/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AdminAuditLogSchema extends BaseModel {
  static $columns = ['action', 'actorUserId', 'entityId', 'entityKind', 'id', 'ipAddress', 'occurredAt', 'payload', 'tenantId'] as const
  $columns = AdminAuditLogSchema.$columns
  @column()
  declare action: string
  @column()
  declare actorUserId: bigint | number | null
  @column()
  declare entityId: bigint | number | null
  @column()
  declare entityKind: string
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare ipAddress: string | null
  @column.dateTime()
  declare occurredAt: DateTime
  @column()
  declare payload: any
  @column()
  declare tenantId: bigint | number
}

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: bigint | number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: bigint | number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class CartAppliedCouponSchema extends BaseModel {
  static $columns = ['cartId', 'codeSnapshot', 'couponId', 'createdAt', 'id', 'tenantId', 'updatedAt'] as const
  $columns = CartAppliedCouponSchema.$columns
  @column()
  declare cartId: bigint | number
  @column()
  declare codeSnapshot: string
  @column()
  declare couponId: bigint | number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare tenantId: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class CartItemSchema extends BaseModel {
  static $columns = ['attributesSnapshot', 'cartId', 'createdAt', 'id', 'priceSnapshot', 'productId', 'quantity', 'tenantId', 'updatedAt', 'variationId'] as const
  $columns = CartItemSchema.$columns
  @column()
  declare attributesSnapshot: any
  @column()
  declare cartId: bigint | number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare priceSnapshot: bigint | number
  @column()
  declare productId: bigint | number
  @column()
  declare quantity: number
  @column()
  declare tenantId: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare variationId: bigint | number | null
}

export class CartSchema extends BaseModel {
  static $columns = ['abandonedAt', 'attributes', 'country', 'createdAt', 'currency', 'customerId', 'id', 'ipAddress', 'lastActivityAt', 'postcode', 'regionId', 'shippingZoneMethodId', 'tenantId', 'token', 'updatedAt', 'userAgent'] as const
  $columns = CartSchema.$columns
  @column.dateTime()
  declare abandonedAt: DateTime | null
  @column()
  declare attributes: any
  @column()
  declare country: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare currency: string
  @column()
  declare customerId: bigint | number | null
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare ipAddress: string | null
  @column.dateTime()
  declare lastActivityAt: DateTime
  @column()
  declare postcode: string | null
  @column()
  declare regionId: bigint | number | null
  @column()
  declare shippingZoneMethodId: bigint | number | null
  @column()
  declare tenantId: bigint | number
  @column()
  declare token: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userAgent: string | null
}

export class CouponBrandConstraintSchema extends BaseModel {
  static $columns = ['brandId', 'couponId', 'createdAt', 'id', 'mode', 'tenantId', 'updatedAt'] as const
  $columns = CouponBrandConstraintSchema.$columns
  @column()
  declare brandId: bigint | number
  @column()
  declare couponId: bigint | number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare mode: string
  @column()
  declare tenantId: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class CouponCategoryConstraintSchema extends BaseModel {
  static $columns = ['categoryId', 'couponId', 'createdAt', 'id', 'mode', 'tenantId', 'updatedAt'] as const
  $columns = CouponCategoryConstraintSchema.$columns
  @column()
  declare categoryId: bigint | number
  @column()
  declare couponId: bigint | number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare mode: string
  @column()
  declare tenantId: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class CouponEmailRestrictionSchema extends BaseModel {
  static $columns = ['couponId', 'createdAt', 'emailPattern', 'id', 'tenantId', 'updatedAt'] as const
  $columns = CouponEmailRestrictionSchema.$columns
  @column()
  declare couponId: bigint | number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare emailPattern: string
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare tenantId: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class CouponProductConstraintSchema extends BaseModel {
  static $columns = ['couponId', 'createdAt', 'id', 'mode', 'productId', 'tenantId', 'updatedAt'] as const
  $columns = CouponProductConstraintSchema.$columns
  @column()
  declare couponId: bigint | number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare mode: string
  @column()
  declare productId: bigint | number
  @column()
  declare tenantId: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class CouponRedemptionSchema extends BaseModel {
  static $columns = ['couponId', 'createdAt', 'customerId', 'emailSnapshot', 'id', 'orderId', 'redeemedAt', 'tenantId', 'updatedAt'] as const
  $columns = CouponRedemptionSchema.$columns
  @column()
  declare couponId: bigint | number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare customerId: bigint | number | null
  @column()
  declare emailSnapshot: string
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare orderId: bigint | number
  @column.dateTime()
  declare redeemedAt: DateTime
  @column()
  declare tenantId: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class CouponTranslationSchema extends BaseModel {
  static $columns = ['couponId', 'createdAt', 'description', 'locale', 'tenantId', 'updatedAt'] as const
  $columns = CouponTranslationSchema.$columns
  @column({ isPrimary: true })
  declare couponId: bigint | number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column()
  declare locale: string
  @column()
  declare tenantId: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class CouponSchema extends BaseModel {
  static $columns = ['amountMinor', 'amountPercent', 'attributes', 'code', 'createdAt', 'deletedAt', 'discountType', 'excludeSaleItems', 'expiresAt', 'freeShipping', 'id', 'individualUse', 'limitUsageToXItems', 'maximumAmount', 'minimumAmount', 'startsAt', 'status', 'tenantId', 'updatedAt', 'usageLimitGlobal', 'usageLimitPerUser'] as const
  $columns = CouponSchema.$columns
  @column()
  declare amountMinor: bigint | number | null
  @column()
  declare amountPercent: string | null
  @column()
  declare attributes: any
  @column()
  declare code: any
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare discountType: string
  @column()
  declare excludeSaleItems: boolean
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare freeShipping: boolean
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare individualUse: boolean
  @column()
  declare limitUsageToXItems: number | null
  @column()
  declare maximumAmount: bigint | number | null
  @column()
  declare minimumAmount: bigint | number | null
  @column.dateTime()
  declare startsAt: DateTime | null
  @column()
  declare status: string
  @column()
  declare tenantId: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare usageLimitGlobal: number | null
  @column()
  declare usageLimitPerUser: number | null
}

export class CurrencySchema extends BaseModel {
  static $columns = ['baseRatio', 'code', 'createdAt', 'decimals', 'enabled', 'id', 'nameEn', 'nameFa', 'ordering', 'position', 'symbol', 'updatedAt'] as const
  $columns = CurrencySchema.$columns
  @column()
  declare baseRatio: number
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare decimals: number
  @column()
  declare enabled: boolean
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare nameEn: string
  @column()
  declare nameFa: string
  @column()
  declare ordering: number
  @column()
  declare position: string
  @column()
  declare symbol: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class CustomerAddressSchema extends BaseModel {
  static $columns = ['addressLine1', 'addressLine2', 'attributes', 'city', 'company', 'country', 'createdAt', 'customerId', 'firstName', 'id', 'isDefault', 'kind', 'label', 'lastName', 'phone', 'postcode', 'regionId', 'regionText', 'tenantId', 'updatedAt'] as const
  $columns = CustomerAddressSchema.$columns
  @column()
  declare addressLine1: string
  @column()
  declare addressLine2: string | null
  @column()
  declare attributes: any
  @column()
  declare city: string
  @column()
  declare company: string | null
  @column()
  declare country: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare customerId: bigint | number
  @column()
  declare firstName: string
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare isDefault: boolean
  @column()
  declare kind: string
  @column()
  declare label: string | null
  @column()
  declare lastName: string
  @column()
  declare phone: string | null
  @column()
  declare postcode: string | null
  @column()
  declare regionId: bigint | number | null
  @column()
  declare regionText: string | null
  @column()
  declare tenantId: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class CustomerDownloadSchema extends BaseModel {
  static $columns = ['createdAt', 'customerId', 'downloadLimit', 'downloadsUsed', 'expiresAt', 'grantedAt', 'id', 'orderId', 'productDownloadId', 'productId', 'tenantId', 'updatedAt'] as const
  $columns = CustomerDownloadSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare customerId: bigint | number
  @column()
  declare downloadLimit: number | null
  @column()
  declare downloadsUsed: number
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column.dateTime()
  declare grantedAt: DateTime
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare orderId: bigint | number | null
  @column()
  declare productDownloadId: bigint | number | null
  @column()
  declare productId: bigint | number
  @column()
  declare tenantId: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class CustomerImpersonationEventSchema extends BaseModel {
  static $columns = ['customerId', 'endedAt', 'id', 'impersonatorUserId', 'ipAddress', 'startedAt', 'tenantId', 'userAgent'] as const
  $columns = CustomerImpersonationEventSchema.$columns
  @column()
  declare customerId: bigint | number
  @column.dateTime()
  declare endedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare impersonatorUserId: bigint | number
  @column()
  declare ipAddress: string | null
  @column.dateTime()
  declare startedAt: DateTime
  @column()
  declare tenantId: bigint | number
  @column()
  declare userAgent: string | null
}

export class CustomerIranProfileSchema extends BaseModel {
  static $columns = ['attributes', 'corporateNationalId', 'createdAt', 'customerId', 'economicCode', 'legalCompanyNameFa', 'nationalId', 'tenantId', 'updatedAt', 'vatTaxpayerStatus'] as const
  $columns = CustomerIranProfileSchema.$columns
  @column()
  declare attributes: any
  @column()
  declare corporateNationalId: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare customerId: bigint | number
  @column()
  declare economicCode: string | null
  @column()
  declare legalCompanyNameFa: string | null
  @column()
  declare nationalId: string | null
  @column()
  declare tenantId: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare vatTaxpayerStatus: string | null
}

export class CustomerMarketingConsentHistorySchema extends BaseModel {
  static $columns = ['actorUserId', 'channel', 'customerId', 'id', 'occurredAt', 'optedIn', 'source', 'tenantId'] as const
  $columns = CustomerMarketingConsentHistorySchema.$columns
  @column()
  declare actorUserId: bigint | number | null
  @column()
  declare channel: string
  @column()
  declare customerId: bigint | number
  @column({ isPrimary: true })
  declare id: bigint | number
  @column.dateTime()
  declare occurredAt: DateTime
  @column()
  declare optedIn: boolean
  @column()
  declare source: string | null
  @column()
  declare tenantId: bigint | number
}

export class CustomerMarketingPrefSchema extends BaseModel {
  static $columns = ['customerId', 'emailOptIn', 'emailOptInAt', 'emailOptInSource', 'phoneCallOptIn', 'phoneCallOptInAt', 'phoneCallOptInSource', 'smsOptIn', 'smsOptInAt', 'smsOptInSource', 'tenantId', 'updatedAt'] as const
  $columns = CustomerMarketingPrefSchema.$columns
  @column({ isPrimary: true })
  declare customerId: bigint | number
  @column()
  declare emailOptIn: boolean
  @column.dateTime()
  declare emailOptInAt: DateTime | null
  @column()
  declare emailOptInSource: string | null
  @column()
  declare phoneCallOptIn: boolean
  @column.dateTime()
  declare phoneCallOptInAt: DateTime | null
  @column()
  declare phoneCallOptInSource: string | null
  @column()
  declare smsOptIn: boolean
  @column.dateTime()
  declare smsOptInAt: DateTime | null
  @column()
  declare smsOptInSource: string | null
  @column()
  declare tenantId: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class CustomerMergeHistorySchema extends BaseModel {
  static $columns = ['actorUserId', 'id', 'mergedCustomerId', 'occurredAt', 'primaryCustomerId', 'snapshot', 'strategy', 'tenantId'] as const
  $columns = CustomerMergeHistorySchema.$columns
  @column()
  declare actorUserId: bigint | number | null
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare mergedCustomerId: bigint | number
  @column.dateTime()
  declare occurredAt: DateTime
  @column()
  declare primaryCustomerId: bigint | number
  @column()
  declare snapshot: any
  @column()
  declare strategy: any
  @column()
  declare tenantId: bigint | number
}

export class CustomerNoteSchema extends BaseModel {
  static $columns = ['authorUserId', 'body', 'createdAt', 'customerId', 'id', 'tenantId', 'updatedAt'] as const
  $columns = CustomerNoteSchema.$columns
  @column()
  declare authorUserId: bigint | number | null
  @column()
  declare body: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare customerId: bigint | number
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare tenantId: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class CustomerSegmentSchema extends BaseModel {
  static $columns = ['createdAt', 'filters', 'id', 'isPinned', 'lastUsedAt', 'name', 'tenantId', 'updatedAt', 'userId'] as const
  $columns = CustomerSegmentSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare filters: any
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare isPinned: boolean
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string
  @column()
  declare tenantId: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: bigint | number
}

export class CustomerStatusHistorySchema extends BaseModel {
  static $columns = ['actorUserId', 'customerId', 'fromStatus', 'id', 'occurredAt', 'reason', 'tenantId', 'toStatus'] as const
  $columns = CustomerStatusHistorySchema.$columns
  @column()
  declare actorUserId: bigint | number | null
  @column()
  declare customerId: bigint | number
  @column()
  declare fromStatus: string | null
  @column({ isPrimary: true })
  declare id: bigint | number
  @column.dateTime()
  declare occurredAt: DateTime
  @column()
  declare reason: string | null
  @column()
  declare tenantId: bigint | number
  @column()
  declare toStatus: string
}

export class CustomerTagPivotSchema extends BaseModel {
  static $columns = ['createdAt', 'customerId', 'tagId', 'tenantId'] as const
  $columns = CustomerTagPivotSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare customerId: bigint | number
  @column()
  declare tagId: bigint | number
  @column()
  declare tenantId: bigint | number
}

export class CustomerTagSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'tenantId'] as const
  $columns = CustomerTagSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare name: string
  @column()
  declare tenantId: bigint | number
}

export class CustomerSchema extends BaseModel {
  static $columns = ['acquisitionChannel', 'attributes', 'countryDefault', 'createdAt', 'deletedAt', 'firstName', 'id', 'isPayingCustomer', 'lastName', 'lastSeenAt', 'phone', 'status', 'tenantId', 'updatedAt', 'userId'] as const
  $columns = CustomerSchema.$columns
  @column()
  declare acquisitionChannel: string | null
  @column()
  declare attributes: any
  @column()
  declare countryDefault: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare firstName: string
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare isPayingCustomer: boolean
  @column()
  declare lastName: string
  @column.dateTime()
  declare lastSeenAt: DateTime | null
  @column()
  declare phone: string | null
  @column()
  declare status: string
  @column()
  declare tenantId: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: bigint | number | null
}

export class InventoryItemSchema extends BaseModel {
  static $columns = ['backorders', 'createdAt', 'id', 'locationId', 'lowStockThreshold', 'manageStock', 'productId', 'stockQuantity', 'stockStatus', 'tenantId', 'updatedAt', 'variationId'] as const
  $columns = InventoryItemSchema.$columns
  @column()
  declare backorders: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare locationId: bigint | number | null
  @column()
  declare lowStockThreshold: number | null
  @column()
  declare manageStock: boolean
  @column()
  declare productId: bigint | number
  @column()
  declare stockQuantity: number
  @column()
  declare stockStatus: string
  @column()
  declare tenantId: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare variationId: bigint | number | null
}

export class InventoryMovementSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'inventoryItemId', 'kind', 'notes', 'occurredAt', 'quantityDelta', 'refId', 'refKind', 'tenantId', 'updatedAt'] as const
  $columns = InventoryMovementSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare inventoryItemId: bigint | number
  @column()
  declare kind: string
  @column()
  declare notes: string | null
  @column.dateTime()
  declare occurredAt: DateTime
  @column()
  declare quantityDelta: number
  @column()
  declare refId: bigint | number | null
  @column()
  declare refKind: string | null
  @column()
  declare tenantId: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class MediaSchema extends BaseModel {
  static $columns = ['alt', 'attributes', 'caption', 'createdAt', 'description', 'filename', 'height', 'id', 'kind', 'mime', 'sizeBytes', 'tenantId', 'title', 'updatedAt', 'uploadedByUserId', 'url', 'width'] as const
  $columns = MediaSchema.$columns
  @column()
  declare alt: string | null
  @column()
  declare attributes: any
  @column()
  declare caption: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column()
  declare filename: string | null
  @column()
  declare height: number | null
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare kind: string
  @column()
  declare mime: string | null
  @column()
  declare sizeBytes: bigint | number | null
  @column()
  declare tenantId: bigint | number
  @column()
  declare title: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare uploadedByUserId: bigint | number | null
  @column()
  declare url: string
  @column()
  declare width: number | null
}

export class OrderAddressIranExtensionSchema extends BaseModel {
  static $columns = ['attributes', 'corporateNationalId', 'createdAt', 'economicCode', 'legalCompanyNameFa', 'nationalId', 'orderAddressId', 'tenantId', 'updatedAt'] as const
  $columns = OrderAddressIranExtensionSchema.$columns
  @column()
  declare attributes: any
  @column()
  declare corporateNationalId: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare economicCode: string | null
  @column()
  declare legalCompanyNameFa: string | null
  @column()
  declare nationalId: string | null
  @column({ isPrimary: true })
  declare orderAddressId: bigint | number
  @column()
  declare tenantId: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class OrderAddressSchema extends BaseModel {
  static $columns = ['addressLine1', 'addressLine2', 'attributes', 'city', 'company', 'country', 'createdAt', 'email', 'firstName', 'id', 'kind', 'lastName', 'orderId', 'phone', 'postcode', 'regionId', 'regionText', 'tenantId', 'updatedAt'] as const
  $columns = OrderAddressSchema.$columns
  @column()
  declare addressLine1: string
  @column()
  declare addressLine2: string | null
  @column()
  declare attributes: any
  @column()
  declare city: string
  @column()
  declare company: string | null
  @column()
  declare country: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string | null
  @column()
  declare firstName: string
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare kind: string
  @column()
  declare lastName: string
  @column()
  declare orderId: bigint | number
  @column()
  declare phone: string | null
  @column()
  declare postcode: string | null
  @column()
  declare regionId: bigint | number | null
  @column()
  declare regionText: string | null
  @column()
  declare tenantId: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class OrderCouponLineSchema extends BaseModel {
  static $columns = ['codeSnapshot', 'couponId', 'createdAt', 'discount', 'discountTax', 'id', 'orderId', 'tenantId', 'updatedAt'] as const
  $columns = OrderCouponLineSchema.$columns
  @column()
  declare codeSnapshot: string
  @column()
  declare couponId: bigint | number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare discount: bigint | number
  @column()
  declare discountTax: bigint | number
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare orderId: bigint | number
  @column()
  declare tenantId: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class OrderDocumentSchema extends BaseModel {
  static $columns = ['amountMinor', 'attributes', 'createdAt', 'currency', 'currencyDisplay', 'id', 'issuedAt', 'issuedByUserId', 'locale', 'number', 'orderId', 'pdfMediaId', 'status', 'tenantId', 'type', 'updatedAt'] as const
  $columns = OrderDocumentSchema.$columns
  @column()
  declare amountMinor: bigint | number
  @column()
  declare attributes: any
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare currency: string
  @column()
  declare currencyDisplay: string
  @column({ isPrimary: true })
  declare id: bigint | number
  @column.dateTime()
  declare issuedAt: DateTime | null
  @column()
  declare issuedByUserId: bigint | number | null
  @column()
  declare locale: string
  @column()
  declare number: bigint | number | null
  @column()
  declare orderId: bigint | number
  @column()
  declare pdfMediaId: bigint | number | null
  @column()
  declare status: string
  @column()
  declare tenantId: bigint | number
  @column()
  declare type: any
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class OrderFeeLineSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'nameSnapshot', 'orderId', 'taxClassIdSnapshot', 'taxable', 'tenantId', 'total', 'totalTax', 'updatedAt'] as const
  $columns = OrderFeeLineSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare nameSnapshot: string
  @column()
  declare orderId: bigint | number
  @column()
  declare taxClassIdSnapshot: bigint | number | null
  @column()
  declare taxable: boolean
  @column()
  declare tenantId: bigint | number
  @column()
  declare total: bigint | number
  @column()
  declare totalTax: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class OrderLineItemTaxSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'lineItemId', 'shippingTaxAmount', 'taxAmount', 'taxRateId', 'tenantId', 'updatedAt'] as const
  $columns = OrderLineItemTaxSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare lineItemId: bigint | number
  @column()
  declare shippingTaxAmount: bigint | number
  @column()
  declare taxAmount: bigint | number
  @column()
  declare taxRateId: bigint | number | null
  @column()
  declare tenantId: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class OrderLineItemSchema extends BaseModel {
  static $columns = ['attributesSnapshot', 'createdAt', 'id', 'nameSnapshot', 'orderId', 'priceSnapshot', 'productId', 'quantity', 'skuSnapshot', 'subtotal', 'subtotalTax', 'taxClassIdSnapshot', 'tenantId', 'total', 'totalTax', 'updatedAt', 'variationId'] as const
  $columns = OrderLineItemSchema.$columns
  @column()
  declare attributesSnapshot: any
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare nameSnapshot: string
  @column()
  declare orderId: bigint | number
  @column()
  declare priceSnapshot: bigint | number
  @column()
  declare productId: bigint | number | null
  @column()
  declare quantity: number
  @column()
  declare skuSnapshot: string | null
  @column()
  declare subtotal: bigint | number
  @column()
  declare subtotalTax: bigint | number
  @column()
  declare taxClassIdSnapshot: bigint | number | null
  @column()
  declare tenantId: bigint | number
  @column()
  declare total: bigint | number
  @column()
  declare totalTax: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare variationId: bigint | number | null
}

export class OrderMetaSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'key', 'orderId', 'tenantId', 'updatedAt', 'value'] as const
  $columns = OrderMetaSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare key: string
  @column()
  declare orderId: bigint | number
  @column()
  declare tenantId: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare value: string
}

export class OrderNoteSchema extends BaseModel {
  static $columns = ['attributes', 'authorUserId', 'body', 'createdAt', 'id', 'orderId', 'tenantId', 'updatedAt', 'visibility'] as const
  $columns = OrderNoteSchema.$columns
  @column()
  declare attributes: any
  @column()
  declare authorUserId: bigint | number | null
  @column()
  declare body: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare orderId: bigint | number
  @column()
  declare tenantId: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare visibility: any
}

export class OrderRefundLineItemSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'orderLineItemId', 'quantity', 'refundAmountMinor', 'refundId', 'refundTaxMinor', 'tenantId', 'updatedAt'] as const
  $columns = OrderRefundLineItemSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare orderLineItemId: bigint | number
  @column()
  declare quantity: number
  @column()
  declare refundAmountMinor: bigint | number
  @column()
  declare refundId: bigint | number
  @column()
  declare refundTaxMinor: bigint | number
  @column()
  declare tenantId: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class OrderRefundSchema extends BaseModel {
  static $columns = ['amountMinor', 'attributes', 'createdAt', 'gatewayRefundId', 'id', 'idempotencyKey', 'orderId', 'processedAt', 'reason', 'refundNumber', 'refundedByUserId', 'restockRequested', 'taxAmountMinor', 'tenantId', 'updatedAt'] as const
  $columns = OrderRefundSchema.$columns
  @column()
  declare amountMinor: bigint | number
  @column()
  declare attributes: any
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare gatewayRefundId: string | null
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare idempotencyKey: string | null
  @column()
  declare orderId: bigint | number
  @column.dateTime()
  declare processedAt: DateTime
  @column()
  declare reason: string | null
  @column()
  declare refundNumber: bigint | number
  @column()
  declare refundedByUserId: bigint | number | null
  @column()
  declare restockRequested: boolean
  @column()
  declare taxAmountMinor: bigint | number
  @column()
  declare tenantId: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class OrderShippingLineSchema extends BaseModel {
  static $columns = ['attributes', 'createdAt', 'id', 'instanceIdSnapshot', 'methodCodeSnapshot', 'methodIdSnapshot', 'orderId', 'tenantId', 'titleSnapshot', 'total', 'totalTax', 'updatedAt'] as const
  $columns = OrderShippingLineSchema.$columns
  @column()
  declare attributes: any
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare instanceIdSnapshot: bigint | number | null
  @column()
  declare methodCodeSnapshot: string
  @column()
  declare methodIdSnapshot: bigint | number | null
  @column()
  declare orderId: bigint | number
  @column()
  declare tenantId: bigint | number
  @column()
  declare titleSnapshot: string
  @column()
  declare total: bigint | number
  @column()
  declare totalTax: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class OrderStatusHistorySchema extends BaseModel {
  static $columns = ['changedByUserId', 'createdAt', 'fromStatus', 'id', 'occurredAt', 'orderId', 'reason', 'tenantId', 'toStatus', 'updatedAt'] as const
  $columns = OrderStatusHistorySchema.$columns
  @column()
  declare changedByUserId: bigint | number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare fromStatus: any | null
  @column({ isPrimary: true })
  declare id: bigint | number
  @column.dateTime()
  declare occurredAt: DateTime
  @column()
  declare orderId: bigint | number
  @column()
  declare reason: string | null
  @column()
  declare tenantId: bigint | number
  @column()
  declare toStatus: any
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class OrderTaxLineSchema extends BaseModel {
  static $columns = ['compoundSnapshot', 'createdAt', 'id', 'labelSnapshot', 'orderId', 'rateCodeSnapshot', 'ratePercentSnapshot', 'shippingTaxTotal', 'taxRateIdSnapshot', 'taxTotal', 'tenantId', 'updatedAt'] as const
  $columns = OrderTaxLineSchema.$columns
  @column()
  declare compoundSnapshot: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare labelSnapshot: string
  @column()
  declare orderId: bigint | number
  @column()
  declare rateCodeSnapshot: string
  @column()
  declare ratePercentSnapshot: string
  @column()
  declare shippingTaxTotal: bigint | number
  @column()
  declare taxRateIdSnapshot: bigint | number | null
  @column()
  declare taxTotal: bigint | number
  @column()
  declare tenantId: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class OrderSchema extends BaseModel {
  static $columns = ['attributes', 'billingEmail', 'cartHash', 'createdAt', 'createdVia', 'currency', 'currencyDisplay', 'customerId', 'customerNote', 'dateCompletedAt', 'datePaidAt', 'deletedAt', 'discountTaxTotal', 'discountTotal', 'feesTaxTotal', 'feesTotal', 'grandTotal', 'id', 'idempotencyKey', 'ipAddress', 'itemsTaxTotal', 'itemsTotal', 'lastPaymentAttemptId', 'orderKey', 'orderNumber', 'paymentGatewayIdSnapshot', 'paymentMethodCodeSnapshot', 'paymentMethodTitleSnapshot', 'pricesIncludeTax', 'shippingTaxTotal', 'shippingTotal', 'status', 'taxTotal', 'tenantId', 'transactionId', 'updatedAt', 'userAgent'] as const
  $columns = OrderSchema.$columns
  @column()
  declare attributes: any
  @column()
  declare billingEmail: string | null
  @column()
  declare cartHash: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdVia: string
  @column()
  declare currency: string
  @column()
  declare currencyDisplay: string
  @column()
  declare customerId: bigint | number | null
  @column()
  declare customerNote: string | null
  @column.dateTime()
  declare dateCompletedAt: DateTime | null
  @column.dateTime()
  declare datePaidAt: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare discountTaxTotal: bigint | number
  @column()
  declare discountTotal: bigint | number
  @column()
  declare feesTaxTotal: bigint | number
  @column()
  declare feesTotal: bigint | number
  @column()
  declare grandTotal: bigint | number
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare idempotencyKey: string | null
  @column()
  declare ipAddress: string | null
  @column()
  declare itemsTaxTotal: bigint | number
  @column()
  declare itemsTotal: bigint | number
  @column()
  declare lastPaymentAttemptId: bigint | number | null
  @column()
  declare orderKey: string | null
  @column()
  declare orderNumber: bigint | number
  @column()
  declare paymentGatewayIdSnapshot: bigint | number | null
  @column()
  declare paymentMethodCodeSnapshot: string | null
  @column()
  declare paymentMethodTitleSnapshot: string | null
  @column()
  declare pricesIncludeTax: boolean
  @column()
  declare shippingTaxTotal: bigint | number
  @column()
  declare shippingTotal: bigint | number
  @column()
  declare status: any
  @column()
  declare taxTotal: bigint | number
  @column()
  declare tenantId: bigint | number
  @column()
  declare transactionId: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userAgent: string | null
}

export class OtpCodeSchema extends BaseModel {
  static $columns = ['attempts', 'channel', 'codeHash', 'consumedAt', 'createdAt', 'expiresAt', 'id', 'identifier', 'purpose', 'tenantId'] as const
  $columns = OtpCodeSchema.$columns
  @column()
  declare attempts: number
  @column()
  declare channel: string
  @column()
  declare codeHash: string
  @column.dateTime()
  declare consumedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare identifier: any
  @column()
  declare purpose: string
  @column()
  declare tenantId: bigint | number
}

export class PasswordResetTokenSchema extends BaseModel {
  static $columns = ['createdAt', 'expiresAt', 'id', 'tokenHash', 'updatedAt', 'usedAt', 'userId'] as const
  $columns = PasswordResetTokenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare tokenHash: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column.dateTime()
  declare usedAt: DateTime | null
  @column()
  declare userId: bigint | number
}

export class PaymentAttemptSchema extends BaseModel {
  static $columns = ['amountMinor', 'createdAt', 'currency', 'errorCode', 'errorMessage', 'gatewayAuthority', 'gatewayCodeSnapshot', 'gatewayId', 'gatewayPayload', 'gatewayTransactionId', 'id', 'idempotencyKey', 'initiatedAt', 'orderId', 'status', 'tenantId', 'updatedAt', 'verifiedAt'] as const
  $columns = PaymentAttemptSchema.$columns
  @column()
  declare amountMinor: bigint | number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare currency: string
  @column()
  declare errorCode: string | null
  @column()
  declare errorMessage: string | null
  @column()
  declare gatewayAuthority: string | null
  @column()
  declare gatewayCodeSnapshot: string
  @column()
  declare gatewayId: bigint | number
  @column()
  declare gatewayPayload: any
  @column()
  declare gatewayTransactionId: string | null
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare idempotencyKey: string | null
  @column.dateTime()
  declare initiatedAt: DateTime
  @column()
  declare orderId: bigint | number
  @column()
  declare status: any
  @column()
  declare tenantId: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column.dateTime()
  declare verifiedAt: DateTime | null
}

export class PaymentGatewaySchema extends BaseModel {
  static $columns = ['attributes', 'code', 'createdAt', 'enabled', 'id', 'ordering', 'settings', 'signedCallback', 'supports', 'tenantId', 'updatedAt', 'webhookSecretEnvKey', 'webhookSignatureHeader'] as const
  $columns = PaymentGatewaySchema.$columns
  @column()
  declare attributes: any
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare enabled: boolean
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare ordering: number
  @column()
  declare settings: any
  @column()
  declare signedCallback: boolean
  @column()
  declare supports: any
  @column()
  declare tenantId: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare webhookSecretEnvKey: string | null
  @column()
  declare webhookSignatureHeader: string | null
}

export class PaymentLinkSchema extends BaseModel {
  static $columns = ['amountMinor', 'attributes', 'code', 'createdAt', 'createdByUserId', 'currency', 'description', 'expiresAt', 'gatewayId', 'id', 'maxUses', 'orderId', 'status', 'tenantId', 'updatedAt', 'usedCount'] as const
  $columns = PaymentLinkSchema.$columns
  @column()
  declare amountMinor: bigint | number
  @column()
  declare attributes: any
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdByUserId: bigint | number | null
  @column()
  declare currency: string
  @column()
  declare description: string | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare gatewayId: bigint | number | null
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare maxUses: number
  @column()
  declare orderId: bigint | number | null
  @column()
  declare status: string
  @column()
  declare tenantId: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare usedCount: number
}

export class PlanSchema extends BaseModel {
  static $columns = ['createdAt', 'dbTier', 'id', 'isDefault', 'key', 'limits', 'name', 'updatedAt'] as const
  $columns = PlanSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare dbTier: string
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare isDefault: boolean
  @column()
  declare key: string
  @column()
  declare limits: any
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class PlatformAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = PlatformAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: bigint | number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: bigint | number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class PlatformUserSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'email', 'id', 'lastLoginAt', 'name', 'passwordHash', 'role', 'updatedAt'] as const
  $columns = PlatformUserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare email: any
  @column({ isPrimary: true })
  declare id: bigint | number
  @column.dateTime()
  declare lastLoginAt: DateTime | null
  @column()
  declare name: string
  @column()
  declare passwordHash: string
  @column()
  declare role: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ProcessedWebhookEventSchema extends BaseModel {
  static $columns = ['createdAt', 'eventId', 'eventKind', 'id', 'orderId', 'outcome', 'payloadHash', 'paymentAttemptId', 'processedAt', 'provider', 'receivedAt', 'tenantId', 'updatedAt'] as const
  $columns = ProcessedWebhookEventSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare eventId: string
  @column()
  declare eventKind: string
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare orderId: bigint | number | null
  @column()
  declare outcome: string
  @column()
  declare payloadHash: string
  @column()
  declare paymentAttemptId: bigint | number | null
  @column.dateTime()
  declare processedAt: DateTime | null
  @column()
  declare provider: string
  @column.dateTime()
  declare receivedAt: DateTime
  @column()
  declare tenantId: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ProductAttributeLinkTermSchema extends BaseModel {
  static $columns = ['createdAt', 'linkId', 'position', 'tenantId', 'termId', 'updatedAt'] as const
  $columns = ProductAttributeLinkTermSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare linkId: bigint | number
  @column()
  declare position: number
  @column()
  declare tenantId: bigint | number
  @column()
  declare termId: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ProductAttributeLinkSchema extends BaseModel {
  static $columns = ['attributeId', 'createdAt', 'displayType', 'id', 'position', 'productId', 'tenantId', 'updatedAt', 'usedForVariation', 'visible'] as const
  $columns = ProductAttributeLinkSchema.$columns
  @column()
  declare attributeId: bigint | number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare displayType: string
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare position: number
  @column()
  declare productId: bigint | number
  @column()
  declare tenantId: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare usedForVariation: boolean
  @column()
  declare visible: boolean
}

export class ProductAttributeTermTranslationSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'locale', 'name', 'slug', 'tenantId', 'termId', 'updatedAt'] as const
  $columns = ProductAttributeTermTranslationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column()
  declare locale: string
  @column()
  declare name: string
  @column()
  declare slug: string
  @column()
  declare tenantId: bigint | number
  @column({ isPrimary: true })
  declare termId: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ProductAttributeTermSchema extends BaseModel {
  static $columns = ['attributeId', 'attributes', 'createdAt', 'id', 'menuOrder', 'tenantId', 'updatedAt'] as const
  $columns = ProductAttributeTermSchema.$columns
  @column()
  declare attributeId: bigint | number
  @column()
  declare attributes: any
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare menuOrder: number
  @column()
  declare tenantId: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ProductAttributeTranslationSchema extends BaseModel {
  static $columns = ['attributeId', 'createdAt', 'locale', 'name', 'tenantId', 'updatedAt'] as const
  $columns = ProductAttributeTranslationSchema.$columns
  @column({ isPrimary: true })
  declare attributeId: bigint | number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare locale: string
  @column()
  declare name: string
  @column()
  declare tenantId: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ProductAttributeSchema extends BaseModel {
  static $columns = ['attributes', 'code', 'createdAt', 'hasArchives', 'id', 'orderBy', 'tenantId', 'updatedAt'] as const
  $columns = ProductAttributeSchema.$columns
  @column()
  declare attributes: any
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare hasArchives: boolean
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare orderBy: string
  @column()
  declare tenantId: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ProductBrandLinkSchema extends BaseModel {
  static $columns = ['brandId', 'createdAt', 'productId', 'tenantId', 'updatedAt'] as const
  $columns = ProductBrandLinkSchema.$columns
  @column()
  declare brandId: bigint | number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare productId: bigint | number
  @column()
  declare tenantId: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ProductBrandTranslationSchema extends BaseModel {
  static $columns = ['brandId', 'createdAt', 'description', 'locale', 'name', 'slug', 'tenantId', 'updatedAt'] as const
  $columns = ProductBrandTranslationSchema.$columns
  @column({ isPrimary: true })
  declare brandId: bigint | number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column()
  declare locale: string
  @column()
  declare name: string
  @column()
  declare slug: string
  @column()
  declare tenantId: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ProductBrandSchema extends BaseModel {
  static $columns = ['attributes', 'createdAt', 'id', 'imageMediaId', 'menuOrder', 'tenantId', 'updatedAt'] as const
  $columns = ProductBrandSchema.$columns
  @column()
  declare attributes: any
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare imageMediaId: bigint | number | null
  @column()
  declare menuOrder: number
  @column()
  declare tenantId: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ProductCategorySchema extends BaseModel {
  static $columns = ['attributes', 'createdAt', 'display', 'id', 'imageMediaId', 'menuOrder', 'parentId', 'tenantId', 'updatedAt'] as const
  $columns = ProductCategorySchema.$columns
  @column()
  declare attributes: any
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare display: string
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare imageMediaId: bigint | number | null
  @column()
  declare menuOrder: number
  @column()
  declare parentId: bigint | number | null
  @column()
  declare tenantId: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ProductCategoryLinkSchema extends BaseModel {
  static $columns = ['categoryId', 'createdAt', 'productId', 'tenantId', 'updatedAt'] as const
  $columns = ProductCategoryLinkSchema.$columns
  @column()
  declare categoryId: bigint | number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare productId: bigint | number
  @column()
  declare tenantId: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ProductCategoryTranslationSchema extends BaseModel {
  static $columns = ['categoryId', 'createdAt', 'description', 'locale', 'name', 'slug', 'tenantId', 'updatedAt'] as const
  $columns = ProductCategoryTranslationSchema.$columns
  @column({ isPrimary: true })
  declare categoryId: bigint | number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column()
  declare locale: string
  @column()
  declare name: string
  @column()
  declare slug: string
  @column()
  declare tenantId: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ProductCrossSellSchema extends BaseModel {
  static $columns = ['createdAt', 'position', 'productId', 'relatedProductId', 'tenantId', 'updatedAt'] as const
  $columns = ProductCrossSellSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare position: number
  @column({ isPrimary: true })
  declare productId: bigint | number
  @column()
  declare relatedProductId: bigint | number
  @column()
  declare tenantId: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ProductCustomAttributeSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'position', 'productId', 'tenantId', 'updatedAt', 'values', 'visible'] as const
  $columns = ProductCustomAttributeSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare name: string
  @column()
  declare position: number
  @column()
  declare productId: bigint | number
  @column()
  declare tenantId: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare values: any
  @column()
  declare visible: boolean
}

export class ProductDownloadSchema extends BaseModel {
  static $columns = ['createdAt', 'downloadExpiryDays', 'downloadLimit', 'fileLabel', 'id', 'mediaId', 'position', 'productId', 'tenantId', 'updatedAt'] as const
  $columns = ProductDownloadSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare downloadExpiryDays: number | null
  @column()
  declare downloadLimit: number | null
  @column()
  declare fileLabel: string
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare mediaId: bigint | number
  @column()
  declare position: number
  @column()
  declare productId: bigint | number
  @column()
  declare tenantId: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ProductExportFilterPresetSchema extends BaseModel {
  static $columns = ['columns', 'createdAt', 'filters', 'formatOptions', 'id', 'isDefault', 'lastUsedAt', 'name', 'tenantId', 'updatedAt', 'userId'] as const
  $columns = ProductExportFilterPresetSchema.$columns
  @column()
  declare columns: any
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare filters: any
  @column()
  declare formatOptions: any
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare isDefault: boolean
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string
  @column()
  declare tenantId: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: bigint | number
}

export class ProductExportSchema extends BaseModel {
  static $columns = ['cancellationRequestedAt', 'columns', 'compressed', 'createdAt', 'downloadExpiresAt', 'downloadTokenHash', 'exception', 'filePath', 'fileSizeBytes', 'filters', 'finishedAt', 'formatOptions', 'id', 'originalFilename', 'presetId', 'processedRows', 'scope', 'startedAt', 'status', 'tenantId', 'totalRows', 'updatedAt', 'userId'] as const
  $columns = ProductExportSchema.$columns
  @column.dateTime()
  declare cancellationRequestedAt: DateTime | null
  @column()
  declare columns: any
  @column()
  declare compressed: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare downloadExpiresAt: DateTime | null
  @column()
  declare downloadTokenHash: string | null
  @column()
  declare exception: string | null
  @column()
  declare filePath: string | null
  @column()
  declare fileSizeBytes: bigint | number
  @column()
  declare filters: any
  @column.dateTime()
  declare finishedAt: DateTime | null
  @column()
  declare formatOptions: any
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare originalFilename: string
  @column()
  declare presetId: bigint | number | null
  @column()
  declare processedRows: number
  @column()
  declare scope: any
  @column.dateTime()
  declare startedAt: DateTime | null
  @column()
  declare status: any
  @column()
  declare tenantId: bigint | number
  @column()
  declare totalRows: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: bigint | number
}

export class ProductFavoriteSchema extends BaseModel {
  static $columns = ['createdAt', 'productId', 'tenantId', 'userId'] as const
  $columns = ProductFavoriteSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare productId: bigint | number
  @column()
  declare tenantId: bigint | number
  @column({ isPrimary: true })
  declare userId: bigint | number
}

export class ProductGroupMemberSchema extends BaseModel {
  static $columns = ['createdAt', 'groupProductId', 'memberProductId', 'position', 'tenantId', 'updatedAt'] as const
  $columns = ProductGroupMemberSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare groupProductId: bigint | number
  @column()
  declare memberProductId: bigint | number
  @column()
  declare position: number
  @column()
  declare tenantId: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ProductImageSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'mediaId', 'position', 'productId', 'tenantId', 'updatedAt'] as const
  $columns = ProductImageSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare mediaId: bigint | number
  @column()
  declare position: number
  @column()
  declare productId: bigint | number
  @column()
  declare tenantId: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ProductImportChangeSchema extends BaseModel {
  static $columns = ['createdAt', 'field', 'id', 'importId', 'newValue', 'oldValue', 'op', 'productId', 'rowNumber', 'sku', 'tenantId'] as const
  $columns = ProductImportChangeSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare field: string
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare importId: bigint | number
  @column()
  declare newValue: string | null
  @column()
  declare oldValue: string | null
  @column()
  declare op: any
  @column()
  declare productId: bigint | number | null
  @column()
  declare rowNumber: number
  @column()
  declare sku: string | null
  @column()
  declare tenantId: bigint | number
}

export class ProductImportErrorSchema extends BaseModel {
  static $columns = ['code', 'columnName', 'createdAt', 'id', 'importId', 'message', 'originalValue', 'retriedAt', 'retriedOutcome', 'rowNumber', 'severity', 'sku', 'tenantId', 'updatedAt'] as const
  $columns = ProductImportErrorSchema.$columns
  @column()
  declare code: string
  @column()
  declare columnName: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare importId: bigint | number
  @column()
  declare message: string
  @column()
  declare originalValue: string | null
  @column.dateTime()
  declare retriedAt: DateTime | null
  @column()
  declare retriedOutcome: string | null
  @column()
  declare rowNumber: number
  @column()
  declare severity: any
  @column()
  declare sku: string | null
  @column()
  declare tenantId: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ProductImportMappingPresetSchema extends BaseModel {
  static $columns = ['createdAt', 'createdByUserId', 'headerHash', 'id', 'lastUsedAt', 'mapping', 'name', 'tenantId', 'updateExisting', 'updatedAt', 'useCount'] as const
  $columns = ProductImportMappingPresetSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdByUserId: bigint | number | null
  @column()
  declare headerHash: string
  @column({ isPrimary: true })
  declare id: bigint | number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare mapping: any
  @column()
  declare name: string
  @column()
  declare tenantId: bigint | number
  @column()
  declare updateExisting: boolean
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare useCount: number
}

export class ProductImportSchema extends BaseModel {
  static $columns = ['cancellationRequestedAt', 'createdAt', 'createdCount', 'detectedDelimiter', 'detectedEncoding', 'errorReportPath', 'exception', 'failedCount', 'filePath', 'fileSizeBytes', 'finishedAt', 'headerHash', 'id', 'mapping', 'newCategoriesCount', 'newTagsCount', 'originalFilename', 'presetId', 'processedRows', 'queuedAt', 'queuedImagesCount', 'rolledBackAt', 'rolledBackByUserId', 'skippedCount', 'snapshotPath', 'startedAt', 'status', 'tenantId', 'totalRows', 'updateExisting', 'updatedAt', 'updatedCount', 'userId'] as const
  $columns = ProductImportSchema.$columns
  @column.dateTime()
  declare cancellationRequestedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdCount: number
  @column()
  declare detectedDelimiter: string
  @column()
  declare detectedEncoding: string
  @column()
  declare errorReportPath: string | null
  @column()
  declare exception: string | null
  @column()
  declare failedCount: number
  @column()
  declare filePath: string
  @column()
  declare fileSizeBytes: bigint | number
  @column.dateTime()
  declare finishedAt: DateTime | null
  @column()
  declare headerHash: string
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare mapping: any
  @column()
  declare newCategoriesCount: number
  @column()
  declare newTagsCount: number
  @column()
  declare originalFilename: string
  @column()
  declare presetId: bigint | number | null
  @column()
  declare processedRows: number
  @column.dateTime()
  declare queuedAt: DateTime
  @column()
  declare queuedImagesCount: number
  @column.dateTime()
  declare rolledBackAt: DateTime | null
  @column()
  declare rolledBackByUserId: bigint | number | null
  @column()
  declare skippedCount: number
  @column()
  declare snapshotPath: string | null
  @column.dateTime()
  declare startedAt: DateTime | null
  @column()
  declare status: any
  @column()
  declare tenantId: bigint | number
  @column()
  declare totalRows: number
  @column()
  declare updateExisting: boolean
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare updatedCount: number
  @column()
  declare userId: bigint | number
}

export class ProductReviewSchema extends BaseModel {
  static $columns = ['body', 'createdAt', 'customerId', 'id', 'productId', 'rating', 'reviewerEmail', 'reviewerName', 'status', 'tenantId', 'updatedAt', 'verified'] as const
  $columns = ProductReviewSchema.$columns
  @column()
  declare body: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare customerId: bigint | number | null
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare productId: bigint | number
  @column()
  declare rating: number
  @column()
  declare reviewerEmail: string
  @column()
  declare reviewerName: string
  @column()
  declare status: string
  @column()
  declare tenantId: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare verified: boolean
}

export class ProductShippingClassTranslationSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'locale', 'name', 'shippingClassId', 'tenantId', 'updatedAt'] as const
  $columns = ProductShippingClassTranslationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column()
  declare locale: string
  @column()
  declare name: string
  @column({ isPrimary: true })
  declare shippingClassId: bigint | number
  @column()
  declare tenantId: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ProductShippingClassSchema extends BaseModel {
  static $columns = ['attributes', 'createdAt', 'id', 'menuOrder', 'slug', 'tenantId', 'updatedAt'] as const
  $columns = ProductShippingClassSchema.$columns
  @column()
  declare attributes: any
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare menuOrder: number
  @column()
  declare slug: string
  @column()
  declare tenantId: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ProductTagLinkSchema extends BaseModel {
  static $columns = ['createdAt', 'productId', 'tagId', 'tenantId', 'updatedAt'] as const
  $columns = ProductTagLinkSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare productId: bigint | number
  @column()
  declare tagId: bigint | number
  @column()
  declare tenantId: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ProductTagTranslationSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'locale', 'name', 'slug', 'tagId', 'tenantId', 'updatedAt'] as const
  $columns = ProductTagTranslationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column()
  declare locale: string
  @column()
  declare name: string
  @column()
  declare slug: string
  @column({ isPrimary: true })
  declare tagId: bigint | number
  @column()
  declare tenantId: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ProductTagSchema extends BaseModel {
  static $columns = ['attributes', 'createdAt', 'id', 'menuOrder', 'tenantId', 'updatedAt'] as const
  $columns = ProductTagSchema.$columns
  @column()
  declare attributes: any
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare menuOrder: number
  @column()
  declare tenantId: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ProductTranslationSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'externalButtonText', 'locale', 'name', 'productId', 'purchaseNote', 'shortDescription', 'slug', 'tenantId', 'updatedAt'] as const
  $columns = ProductTranslationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column()
  declare externalButtonText: string | null
  @column()
  declare locale: string
  @column()
  declare name: string
  @column({ isPrimary: true })
  declare productId: bigint | number
  @column()
  declare purchaseNote: string | null
  @column()
  declare shortDescription: string | null
  @column()
  declare slug: string
  @column()
  declare tenantId: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ProductUpsellSchema extends BaseModel {
  static $columns = ['createdAt', 'position', 'productId', 'relatedProductId', 'tenantId', 'updatedAt'] as const
  $columns = ProductUpsellSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare position: number
  @column({ isPrimary: true })
  declare productId: bigint | number
  @column()
  declare relatedProductId: bigint | number
  @column()
  declare tenantId: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ProductVariationAttributeSchema extends BaseModel {
  static $columns = ['attributeId', 'createdAt', 'tenantId', 'termId', 'updatedAt', 'variationId'] as const
  $columns = ProductVariationAttributeSchema.$columns
  @column()
  declare attributeId: bigint | number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare tenantId: bigint | number
  @column()
  declare termId: bigint | number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column({ isPrimary: true })
  declare variationId: bigint | number
}

export class ProductVariationTranslationSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'locale', 'tenantId', 'updatedAt', 'variationId'] as const
  $columns = ProductVariationTranslationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column()
  declare locale: string
  @column()
  declare tenantId: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column({ isPrimary: true })
  declare variationId: bigint | number
}

export class ProductVariationSchema extends BaseModel {
  static $columns = ['attributes', 'createdAt', 'deletedAt', 'downloadable', 'gtin', 'heightMm', 'id', 'imageMediaId', 'lengthMm', 'manageStockMode', 'menuOrder', 'productId', 'regularPrice', 'saleEndsAt', 'salePrice', 'saleStartsAt', 'sku', 'status', 'taxClassId', 'tenantId', 'updatedAt', 'virtual', 'weightGrams', 'widthMm'] as const
  $columns = ProductVariationSchema.$columns
  @column()
  declare attributes: any
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare downloadable: boolean
  @column()
  declare gtin: string | null
  @column()
  declare heightMm: number | null
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare imageMediaId: bigint | number | null
  @column()
  declare lengthMm: number | null
  @column()
  declare manageStockMode: string
  @column()
  declare menuOrder: number
  @column()
  declare productId: bigint | number
  @column()
  declare regularPrice: bigint | number | null
  @column.dateTime()
  declare saleEndsAt: DateTime | null
  @column()
  declare salePrice: bigint | number | null
  @column.dateTime()
  declare saleStartsAt: DateTime | null
  @column()
  declare sku: string | null
  @column()
  declare status: string
  @column()
  declare taxClassId: bigint | number | null
  @column()
  declare tenantId: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare virtual: boolean
  @column()
  declare weightGrams: number | null
  @column()
  declare widthMm: number | null
}

export class ProductSchema extends BaseModel {
  static $columns = ['attributes', 'catalogVisibility', 'createdAt', 'defaultVariationId', 'deletedAt', 'downloadable', 'externalUrl', 'featured', 'globalUniqueId', 'gtin', 'heightMm', 'id', 'lengthMm', 'menuOrder', 'posAvailable', 'regularPrice', 'reviewsAllowed', 'saleEndsAt', 'salePrice', 'saleStartsAt', 'shippingClassId', 'sku', 'soldIndividually', 'status', 'taxClassId', 'taxStatus', 'tenantId', 'type', 'updatedAt', 'virtual', 'weightGrams', 'widthMm'] as const
  $columns = ProductSchema.$columns
  @column()
  declare attributes: any
  @column()
  declare catalogVisibility: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare defaultVariationId: bigint | number | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare downloadable: boolean
  @column()
  declare externalUrl: string | null
  @column()
  declare featured: boolean
  @column()
  declare globalUniqueId: string | null
  @column()
  declare gtin: string | null
  @column()
  declare heightMm: number | null
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare lengthMm: number | null
  @column()
  declare menuOrder: number
  @column()
  declare posAvailable: boolean
  @column()
  declare regularPrice: bigint | number | null
  @column()
  declare reviewsAllowed: boolean
  @column.dateTime()
  declare saleEndsAt: DateTime | null
  @column()
  declare salePrice: bigint | number | null
  @column.dateTime()
  declare saleStartsAt: DateTime | null
  @column()
  declare shippingClassId: bigint | number | null
  @column()
  declare sku: string | null
  @column()
  declare soldIndividually: boolean
  @column()
  declare status: string
  @column()
  declare taxClassId: bigint | number | null
  @column()
  declare taxStatus: string
  @column()
  declare tenantId: bigint | number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare virtual: boolean
  @column()
  declare weightGrams: number | null
  @column()
  declare widthMm: number | null
}

export class QueueJobSchema extends BaseModel {
  static $columns = ['acquiredAt', 'data', 'error', 'executeAt', 'finishedAt', 'id', 'queue', 'score', 'status', 'workerId'] as const
  $columns = QueueJobSchema.$columns
  @column()
  declare acquiredAt: bigint | number | null
  @column()
  declare data: string
  @column()
  declare error: string | null
  @column()
  declare executeAt: bigint | number | null
  @column()
  declare finishedAt: bigint | number | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare queue: string
  @column()
  declare score: bigint | number | null
  @column()
  declare status: string
  @column()
  declare workerId: string | null
}

export class QueueScheduleSchema extends BaseModel {
  static $columns = ['createdAt', 'cronExpression', 'everyMs', 'fromDate', 'id', 'lastRunAt', 'name', 'nextRunAt', 'payload', 'runCount', 'runLimit', 'status', 'timezone', 'toDate'] as const
  $columns = QueueScheduleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare cronExpression: string | null
  @column()
  declare everyMs: bigint | number | null
  @column.dateTime()
  declare fromDate: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare lastRunAt: DateTime | null
  @column()
  declare name: string
  @column.dateTime()
  declare nextRunAt: DateTime | null
  @column()
  declare payload: string
  @column()
  declare runCount: number
  @column()
  declare runLimit: number | null
  @column()
  declare status: string
  @column()
  declare timezone: string
  @column.dateTime()
  declare toDate: DateTime | null
}

export class RegionTranslationSchema extends BaseModel {
  static $columns = ['createdAt', 'locale', 'name', 'regionId', 'updatedAt'] as const
  $columns = RegionTranslationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare locale: string
  @column()
  declare name: string
  @column({ isPrimary: true })
  declare regionId: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class RegionSchema extends BaseModel {
  static $columns = ['attributes', 'code', 'countryCode', 'createdAt', 'id', 'ordering', 'parentId', 'updatedAt'] as const
  $columns = RegionSchema.$columns
  @column()
  declare attributes: any
  @column()
  declare code: string
  @column()
  declare countryCode: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare ordering: number
  @column()
  declare parentId: bigint | number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class SettingSchema extends BaseModel {
  static $columns = ['createdAt', 'groupKey', 'key', 'tenantId', 'type', 'updatedAt', 'value'] as const
  $columns = SettingSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare groupKey: string
  @column()
  declare key: string
  @column()
  declare tenantId: bigint | number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare value: any
}

export class ShippingMethodSchema extends BaseModel {
  static $columns = ['code', 'createdAt', 'descriptionDefault', 'id', 'settingsSchema', 'tenantId', 'titleDefault', 'updatedAt'] as const
  $columns = ShippingMethodSchema.$columns
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare descriptionDefault: string | null
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare settingsSchema: any
  @column()
  declare tenantId: bigint | number
  @column()
  declare titleDefault: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ShippingZoneLocationSchema extends BaseModel {
  static $columns = ['code', 'createdAt', 'id', 'tenantId', 'type', 'updatedAt', 'zoneId'] as const
  $columns = ShippingZoneLocationSchema.$columns
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare tenantId: bigint | number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare zoneId: bigint | number
}

export class ShippingZoneMethodSchema extends BaseModel {
  static $columns = ['createdAt', 'enabled', 'id', 'methodId', 'ordering', 'settings', 'tenantId', 'titleOverride', 'updatedAt', 'zoneId'] as const
  $columns = ShippingZoneMethodSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare enabled: boolean
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare methodId: bigint | number
  @column()
  declare ordering: number
  @column()
  declare settings: any
  @column()
  declare tenantId: bigint | number
  @column()
  declare titleOverride: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare zoneId: bigint | number
}

export class ShippingZoneSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'isFallback', 'name', 'tenantId', 'updatedAt'] as const
  $columns = ShippingZoneSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare isFallback: boolean
  @column()
  declare name: string
  @column()
  declare tenantId: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class TaxClassSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'slug', 'tenantId', 'updatedAt'] as const
  $columns = TaxClassSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare name: string
  @column()
  declare slug: string
  @column()
  declare tenantId: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class TaxRateSchema extends BaseModel {
  static $columns = ['appliesToShipping', 'cities', 'compound', 'country', 'createdAt', 'id', 'label', 'ordering', 'postcodes', 'priority', 'rate', 'regionId', 'taxClassId', 'tenantId', 'updatedAt'] as const
  $columns = TaxRateSchema.$columns
  @column()
  declare appliesToShipping: boolean
  @column()
  declare cities: any | null
  @column()
  declare compound: boolean
  @column()
  declare country: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare label: string
  @column()
  declare ordering: number
  @column()
  declare postcodes: any | null
  @column()
  declare priority: number
  @column()
  declare rate: string
  @column()
  declare regionId: bigint | number | null
  @column()
  declare taxClassId: bigint | number
  @column()
  declare tenantId: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class TenantDomainSchema extends BaseModel {
  static $columns = ['createdAt', 'domain', 'id', 'isPrimary', 'kind', 'tenantId', 'tlsStatus', 'updatedAt', 'verifiedAt'] as const
  $columns = TenantDomainSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare domain: any
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare isPrimary: boolean
  @column()
  declare kind: string
  @column()
  declare tenantId: bigint | number
  @column()
  declare tlsStatus: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column.dateTime()
  declare verifiedAt: DateTime | null
}

export class TenantImpersonationEventSchema extends BaseModel {
  static $columns = ['endedAt', 'id', 'ipAddress', 'platformUserId', 'reason', 'startedAt', 'targetUserId', 'tenantId'] as const
  $columns = TenantImpersonationEventSchema.$columns
  @column.dateTime()
  declare endedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare ipAddress: string | null
  @column()
  declare platformUserId: bigint | number | null
  @column()
  declare reason: string | null
  @column.dateTime()
  declare startedAt: DateTime
  @column()
  declare targetUserId: bigint | number
  @column()
  declare tenantId: bigint | number
}

export class TenantNumberCounterSchema extends BaseModel {
  static $columns = ['createdAt', 'kind', 'nextValue', 'tenantId', 'updatedAt'] as const
  $columns = TenantNumberCounterSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare kind: string
  @column()
  declare nextValue: bigint | number
  @column({ isPrimary: true })
  declare tenantId: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class TenantUsageDailySchema extends BaseModel {
  static $columns = ['createdAt', 'day', 'id', 'metric', 'tenantId', 'updatedAt', 'value'] as const
  $columns = TenantUsageDailySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare day: DateTime
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare metric: string
  @column()
  declare tenantId: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare value: bigint | number
}

export class TenantSchema extends BaseModel {
  static $columns = ['attributes', 'connectionName', 'createdAt', 'currencyCode', 'dbTier', 'deletedAt', 'id', 'name', 'planId', 'primaryLocale', 'slug', 'status', 'templateKey', 'updatedAt'] as const
  $columns = TenantSchema.$columns
  @column()
  declare attributes: any
  @column()
  declare connectionName: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare currencyCode: string
  @column()
  declare dbTier: string
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare name: string
  @column()
  declare planId: bigint | number
  @column()
  declare primaryLocale: string
  @column()
  declare slug: any
  @column()
  declare status: string
  @column()
  declare templateKey: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'email', 'id', 'lastLoginAt', 'locale', 'passwordHash', 'phone', 'role', 'tenantId', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare email: any | null
  @column({ isPrimary: true })
  declare id: bigint | number
  @column.dateTime()
  declare lastLoginAt: DateTime | null
  @column()
  declare locale: string
  @column()
  declare passwordHash: string
  @column()
  declare phone: string | null
  @column()
  declare role: string
  @column()
  declare tenantId: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}
